const Q = require('./_q')('Animaux');
module.exports = [
  Q('Citez un animal de compagnie.', 'facile', [
    ['Chien', 40, 'chiot'],
    ['Chat', 35, 'chaton'],
    ['Lapin', 10, ''],
    ['Poisson rouge', 8, 'poisson'],
    ['Hamster', 7, 'cochon d’inde|cochon d inde'],
  ]),
  Q('Citez un animal de la savane.', 'facile', [
    ['Lion', 34, 'lionne'],
    ['Éléphant', 22, ''],
    ['Girafe', 20, ''],
    ['Zèbre', 14, ''],
    ['Hippopotame', 10, 'hippo'],
  ]),
  Q('Citez un animal qui vit dans la mer.', 'facile', [
    ['Requin', 30, ''],
    ['Dauphin', 26, ''],
    ['Baleine', 20, ''],
    ['Poisson', 14, 'poissons'],
    ['Pieuvre', 10, 'poulpe'],
  ]),
  Q('Citez un animal qui fait peur.', 'facile', [
    ['Araignée', 34, ''],
    ['Serpent', 30, 'vipère|cobra'],
    ['Requin', 14, ''],
    ['Loup', 12, ''],
    ['Rat', 10, 'souris'],
  ]),
  Q('Citez un oiseau.', 'moyen', [
    ['Pigeon', 26, ''],
    ['Moineau', 18, ''],
    ['Aigle', 16, ''],
    ['Perroquet', 14, ''],
    ['Merle', 13, ''],
    ['Mouette', 13, 'goéland'],
  ]),
  Q('Citez un animal que l’on trouve dans la forêt.', 'moyen', [
    ['Cerf', 26, 'biche|daim|chevreuil'],
    ['Sanglier', 22, ''],
    ['Renard', 18, ''],
    ['Écureuil', 15, ''],
    ['Loup', 11, ''],
    ['Hibou', 8, 'chouette'],
  ]),
  Q('Citez un animal qui est lent.', 'moyen', [
    ['Escargot', 38, 'escargots|limace'],
    ['Tortue', 34, ''],
    ['Paresseux', 18, ''],
    ['Koala', 5, ''],
    ['Vache', 5, ''],
  ]),
  Q('Citez un animal que l’on voit au zoo.', 'difficile', [
    ['Lion', 22, ''],
    ['Girafe', 18, ''],
    ['Éléphant', 16, ''],
    ['Singe', 14, 'gorille|chimpanzé|orang outan'],
    ['Pingouin', 10, 'manchot'],
    ['Tigre', 9, ''],
    ['Ours', 6, 'panda|ours polaire'],
    ['Flamant rose', 5, 'flamant'],
  ]),
  Q('Citez un animal qui pique ou qui mord.', 'difficile', [
    ['Moustique', 28, ''],
    ['Guêpe', 20, 'frelon'],
    ['Abeille', 16, ''],
    ['Serpent', 12, 'vipère'],
    ['Méduse', 9, ''],
    ['Araignée', 7, ''],
    ['Scorpion', 5, ''],
    ['Tique', 3, ''],
  ]),
];
