const Q = require('./_q')('Cinéma');
module.exports = [
  Q('Citez quelque chose que l’on mange au cinéma.', 'facile', [
    ['Pop-corn', 60, 'pop corn|popcorn'],
    ['Bonbons', 16, 'bonbon|confiseries'],
    ['Glace', 10, 'esquimau|glaces'],
    ['Chips', 8, ''],
    ['Nachos', 6, ''],
  ]),
  Q('Citez un super-héros.', 'facile', [
    ['Superman', 28, ''],
    ['Spider-Man', 26, 'spiderman|spider man|l’homme araignée'],
    ['Batman', 22, ''],
    ['Iron Man', 13, 'ironman'],
    ['Wonder Woman', 11, ''],
  ]),
  Q('Citez un genre de film.', 'facile', [
    ['Comédie', 30, 'film drôle|humour'],
    ['Action', 24, 'film d’action'],
    ['Horreur', 20, 'épouvante|film d’horreur|film qui fait peur'],
    ['Science-fiction', 14, 'science fiction|sf'],
    ['Drame', 12, ''],
  ]),
  Q('Citez un acteur ou une actrice français célèbre.', 'moyen', [
    ['Jean Dujardin', 22, 'dujardin'],
    ['Omar Sy', 20, ''],
    ['Gérard Depardieu', 16, 'depardieu'],
    ['Marion Cotillard', 15, 'cotillard'],
    ['Louis de Funès', 15, 'de funès|funès'],
    ['Audrey Tautou', 12, 'tautou'],
  ]),
  Q('Citez une chose qui gêne au cinéma.', 'moyen', [
    ['Les gens qui parlent', 34, 'bavards|parler|bruit|gens bavards'],
    ['Un téléphone qui sonne', 22, 'téléphone|écran allumé'],
    ['Quelqu’un de grand devant', 18, 'grand devant|tête devant|personne devant'],
    ['Le bruit du pop-corn', 12, 'pop corn|mâcher|bruit de bouche'],
    ['Les coups de pied dans le siège', 8, 'coups de pied|siège'],
    ['Les publicités', 6, 'pubs|publicité|bandes annonces'],
  ]),
  Q('Citez un film de Disney.', 'moyen', [
    ['Le Roi Lion', 26, 'roi lion'],
    ['Blanche-Neige', 18, 'blanche neige'],
    ['Cendrillon', 15, ''],
    ['La Petite Sirène', 14, 'petite sirène|ariel'],
    ['Aladdin', 14, 'aladin'],
    ['La Belle et la Bête', 13, 'belle et la bête'],
  ]),
  Q('Citez un méchant célèbre de cinéma.', 'difficile', [
    ['Dark Vador', 32, 'vador|darth vader'],
    ['Le Joker', 20, 'joker'],
    ['Voldemort', 16, ''],
    ['Hannibal Lecter', 9, 'hannibal|lecter'],
    ['Scar', 8, ''],
    ['Thanos', 6, ''],
    ['Freddy Krueger', 5, 'freddy'],
    ['Cruella', 4, 'cruella d enfer'],
  ]),
  Q('Citez une saga de films célèbre.', 'difficile', [
    ['Star Wars', 30, 'la guerre des étoiles'],
    ['Harry Potter', 26, 'potter'],
    ['Le Seigneur des anneaux', 14, 'seigneur des anneaux'],
    ['James Bond', 10, '007|bond'],
    ['Fast and Furious', 7, 'fast & furious'],
    ['Jurassic Park', 6, 'jurassic world'],
    ['Rocky', 4, ''],
    ['Indiana Jones', 3, 'indiana'],
  ]),
  Q('Citez quelque chose que l’on voit dans un western.', 'difficile', [
    ['Des cowboys', 28, 'cowboy|cow boy|cow-boys'],
    ['Des chevaux', 22, 'cheval'],
    ['Un saloon', 14, 'saloon|bar'],
    ['Des pistolets', 12, 'pistolet|revolver|colt|armes'],
    ['Un shérif', 10, 'shérif|étoile de shérif'],
    ['Le désert', 6, 'désert|cactus'],
    ['Un duel', 5, 'duel'],
    ['Un chapeau', 3, 'chapeau|stetson'],
  ]),
];
