const Q = require('./_q')('École');
module.exports = [
  Q('Citez quelque chose que l’on trouve dans une trousse.', 'facile', [
    ['Stylo', 34, 'stylos|bic|stylo bille'],
    ['Crayon à papier', 22, 'crayon|crayon de papier|crayon gris'],
    ['Gomme', 18, ''],
    ['Règle', 14, ''],
    ['Taille-crayon', 12, 'taille crayon'],
  ]),
  Q('Citez quelque chose que l’on met dans son cartable.', 'facile', [
    ['Cahiers', 30, 'cahier'],
    ['Livres', 24, 'livre|manuels|manuel'],
    ['Trousse', 22, ''],
    ['Goûter', 14, 'gâteaux|collation'],
    ['Agenda', 10, 'cahier de textes|carnet de liaison'],
  ]),
  Q('Citez une activité de la récréation.', 'facile', [
    ['Jouer au foot', 30, 'foot|football|ballon'],
    ['Jouer à chat', 25, 'chat|loup|le loup'],
    ['Discuter', 18, 'parler|bavarder'],
    ['Jouer aux billes', 14, 'billes'],
    ['Sauter à la corde', 13, 'corde à sauter|corde|élastique'],
  ]),
  Q('Citez une excuse pour ne pas avoir fait ses devoirs.', 'moyen', [
    ['Le chien les a mangés', 30, 'chien|mon chien'],
    ['J’ai oublié', 26, 'oublié|oubli'],
    ['J’étais malade', 16, 'malade'],
    ['Je n’ai pas compris', 12, 'pas compris|trop difficile'],
    ['Je les ai laissés à la maison', 10, 'à la maison|oublié à la maison'],
    ['Panne d’internet', 6, 'internet|ordinateur en panne|plus d’internet'],
  ]),
  Q('Citez un personnage que l’on croise dans une école.', 'moyen', [
    ['Le professeur', 38, 'prof|maîtresse|maître|instituteur|enseignant'],
    ['Le directeur', 22, 'directrice|principal|proviseur'],
    ['Les élèves', 16, 'élève|enfants'],
    ['Le surveillant', 12, 'pion|surveillante|cpe'],
    ['La cantinière', 7, 'cantine|dame de cantine'],
    ['L’infirmière', 5, 'infirmier'],
  ]),
  Q('Citez une sortie scolaire.', 'moyen', [
    ['Le musée', 30, 'musée|exposition'],
    ['Le zoo', 20, 'zoo|parc animalier'],
    ['Le cinéma', 15, 'ciné'],
    ['La ferme', 13, 'ferme pédagogique'],
    ['Le théâtre', 12, 'spectacle'],
    ['La classe verte', 10, 'classe de neige|classe découverte|voyage scolaire'],
  ]),
  Q('Citez quelque chose qui fait peur aux élèves.', 'difficile', [
    ['Une interrogation surprise', 26, 'interro|interrogation|contrôle|interro surprise'],
    ['Le bulletin', 20, 'bulletin|notes|mauvaise note'],
    ['Passer au tableau', 16, 'tableau'],
    ['Le directeur', 12, 'bureau du directeur|convoqué'],
    ['Les examens', 10, 'examen|bac|brevet'],
    ['Être puni', 7, 'punition|colle|retenue'],
    ['Les piqûres', 5, 'vaccin|visite médicale'],
    ['La rentrée', 4, ''],
  ]),
  Q('Citez une matière que les élèves détestent.', 'difficile', [
    ['Les maths', 36, 'maths|mathématiques|math'],
    ['L’histoire-géo', 16, 'histoire|géographie|histoire géo'],
    ['La physique-chimie', 14, 'physique|chimie|physique chimie'],
    ['Le français', 10, 'français|grammaire|orthographe|dictée'],
    ['Les langues', 9, 'anglais|allemand|espagnol'],
    ['Le sport', 7, 'eps|gym'],
    ['La philosophie', 5, 'philo'],
    ['La musique', 3, 'flûte|éducation musicale'],
  ]),
  Q('Citez un objet que l’on oublie souvent à l’école.', 'difficile', [
    ['Une veste', 28, 'veste|manteau|blouson|pull'],
    ['Une trousse', 18, 'trousse'],
    ['Un cahier', 14, 'cahier|cahiers'],
    ['Une gourde', 12, 'gourde|bouteille d’eau'],
    ['Les affaires de sport', 10, 'sport|baskets|tenue de sport'],
    ['Une calculatrice', 8, 'calculatrice|calculette'],
    ['Un livre', 6, 'livre|manuel'],
    ['Un parapluie', 4, 'parapluie'],
  ]),
];
