const Q = require('./_q')('Enfants');
module.exports = [
  Q('Citez un jouet que tous les enfants connaissent.', 'facile', [
    ['Des Lego', 30, 'lego|legos|briques'],
    ['Une poupée', 24, 'poupée|barbie|poupées'],
    ['Une peluche', 18, 'peluche|doudou|nounours|ours en peluche'],
    ['Des petites voitures', 16, 'voitures|petite voiture'],
    ['Un ballon', 12, 'ballon|balle'],
  ]),
  Q('Citez un dessin animé pour enfants.', 'facile', [
    ['Pat’ Patrouille', 28, 'pat patrouille|paw patrol'],
    ['Peppa Pig', 24, 'peppa'],
    ['Les Schtroumpfs', 16, 'schtroumpfs|schtroumpf'],
    ['Bob l’éponge', 16, 'bob|bob l éponge'],
    ['Tchoupi', 16, 't choupi'],
  ]),
  Q('Citez une chose que les enfants font à la piscine.', 'moyen', [
    ['Sauter dans l’eau', 30, 'sauter|plonger|plongeon'],
    ['Éclabousser', 20, 'arroser|éclaboussures'],
    ['Jouer avec des frites', 16, 'frites|frite|bouée|brassards'],
    ['Faire le toboggan', 14, 'toboggan'],
    ['Faire pipi dans l’eau', 12, 'pipi'],
    ['Nager sous l’eau', 8, 'sous l’eau|apnée'],
  ]),
  Q('Citez une question que les enfants posent tout le temps.', 'moyen', [
    ['Pourquoi ?', 38, 'pourquoi'],
    ['On arrive quand ?', 24, 'on arrive quand|c’est encore loin|quand est ce qu on arrive'],
    ['Je peux avoir un bonbon ?', 12, 'bonbon|gâteau'],
    ['On mange quoi ?', 10, 'on mange quoi|j’ai faim'],
    ['Je peux jouer ?', 9, 'jouer|je peux jouer|écrans'],
    ['Comment on fait les bébés ?', 7, 'bébés|bébé'],
  ]),
  Q('Citez un conte de fées.', 'moyen', [
    ['Cendrillon', 26, ''],
    ['Le Petit Chaperon rouge', 24, 'petit chaperon rouge|chaperon rouge'],
    ['Blanche-Neige', 18, 'blanche neige'],
    ['La Belle au bois dormant', 14, 'belle au bois dormant'],
    ['Hansel et Gretel', 10, 'hansel|gretel'],
    ['Le Petit Poucet', 8, 'petit poucet|poucet'],
  ]),
  Q('Citez quelque chose qu’un enfant met dans sa bouche alors qu’il ne faut pas.', 'difficile', [
    ['Ses doigts', 26, 'doigts|pouce|doigt'],
    ['Des jouets', 20, 'jouet|jouets|lego'],
    ['De la terre', 14, 'terre|sable|boue'],
    ['Un crayon', 12, 'crayon|feutre|stylo'],
    ['Des pièces de monnaie', 10, 'pièce|pièces|argent'],
    ['Des cailloux', 8, 'caillou'],
    ['Des insectes', 6, 'insecte|fourmi|vers de terre'],
    ['Ses chaussures', 4, 'chaussure|chaussettes'],
  ]),
  Q('Citez une activité pour occuper des enfants un jour de pluie.', 'difficile', [
    ['Dessiner', 26, 'dessin|coloriage|colorier'],
    ['Jeux de société', 20, 'jeu de société|jeux|cartes'],
    ['Regarder un film', 16, 'film|dessin animé|télé'],
    ['Faire un gâteau', 12, 'gâteau|cuisine|pâtisserie'],
    ['Construire une cabane', 9, 'cabane'],
    ['Pâte à modeler', 7, 'pâte à sel|modelage'],
    ['Lire une histoire', 6, 'lire|histoire|livre'],
    ['Faire un puzzle', 4, 'puzzle'],
  ]),
  Q('Citez une chose qui fait pleurer un bébé.', 'difficile', [
    ['La faim', 34, 'faim|il a faim'],
    ['La fatigue', 20, 'fatigue|sommeil|fatigué'],
    ['Une couche sale', 16, 'couche|change'],
    ['Les dents', 12, 'dents qui poussent|poussée dentaire'],
    ['Les coliques', 8, 'mal au ventre|colique'],
    ['Avoir peur', 5, 'peur|bruit'],
    ['Avoir froid', 3, 'froid|chaud'],
    ['Le bain', 2, ''],
  ]),
];
