const Q = require('./_q')('Famille');
module.exports = [
  Q('Citez un membre de la famille.', 'facile', [
    ['Mère', 30, 'maman|mère'],
    ['Père', 26, 'papa'],
    ['Frère', 15, ''],
    ['Sœur', 14, 'soeur'],
    ['Grand-mère', 15, 'mamie|grand mère|mémé|grand-parents'],
  ]),
  Q('Citez quelque chose que les parents disent souvent à leurs enfants.', 'facile', [
    ['Range ta chambre', 30, 'range ta chambre|ranger sa chambre|range'],
    ['Va te coucher', 22, 'au lit|va au lit|dodo'],
    ['Fais tes devoirs', 18, 'devoirs|tes devoirs'],
    ['Brosse-toi les dents', 16, 'brosse toi les dents|les dents'],
    ['Lâche ton téléphone', 14, 'pose ton téléphone|les écrans|arrête les écrans'],
  ]),
  Q('Citez une occasion où toute la famille se réunit.', 'facile', [
    ['Noël', 40, 'réveillon'],
    ['Un anniversaire', 25, 'anniversaire'],
    ['Un mariage', 15, 'mariage|noces'],
    ['Pâques', 10, ''],
    ['Un enterrement', 10, 'enterrement|funérailles|obsèques'],
  ]),
  Q('Citez quelque chose que fait souvent une grand-mère.', 'moyen', [
    ['Cuisiner', 34, 'faire à manger|faire la cuisine|des gâteaux|pâtisserie'],
    ['Tricoter', 24, 'tricot'],
    ['Donner des bonbons', 14, 'bonbons|friandises|gâter les enfants'],
    ['Raconter des histoires', 11, 'histoires|raconter'],
    ['Faire des câlins', 9, 'câlins|bisous'],
    ['Jardiner', 8, 'jardin|jardinage'],
  ]),
  Q('Citez une source de dispute entre frères et sœurs.', 'moyen', [
    ['La télécommande', 26, 'télé|télévision|choisir le programme'],
    ['Les jouets', 22, 'jouet|prêter ses jouets'],
    ['La salle de bain', 14, 'salle de bain|la douche'],
    ['La place à l’avant de la voiture', 14, 'place devant|devant|place avant|siège avant'],
    ['Les vêtements', 12, 'vêtement|habits|fringues'],
    ['La console', 12, 'jeux vidéo|manette'],
  ]),
  Q('Citez une tradition de Noël en famille.', 'moyen', [
    ['Décorer le sapin', 34, 'sapin|arbre de noël'],
    ['Ouvrir les cadeaux', 28, 'cadeaux|cadeau'],
    ['Le repas de Noël', 16, 'repas|réveillon|dinde|bûche'],
    ['Attendre le Père Noël', 10, 'père noël'],
    ['Le calendrier de l’Avent', 7, 'calendrier de l avent|calendrier'],
    ['Aller à la messe', 5, 'messe|église'],
  ]),
  Q('Citez une activité à faire en famille le week-end.', 'difficile', [
    ['Une promenade', 26, 'promenade|balade|marcher|randonnée'],
    ['Un jeu de société', 20, 'jeux de société|jeu de société|jouer aux cartes'],
    ['Aller au cinéma', 15, 'cinéma|ciné|film'],
    ['Un pique-nique', 11, 'pique nique|piquenique'],
    ['Aller au parc', 9, 'parc|jardin public'],
    ['Faire du vélo', 8, 'vélo|balade à vélo'],
    ['Aller au restaurant', 6, 'restaurant|resto'],
    ['Aller à la piscine', 5, 'piscine|nager'],
  ]),
  Q('Citez quelque chose que l’on hérite de ses parents.', 'difficile', [
    ['La maison', 26, 'maison|appartement|logement'],
    ['De l’argent', 22, 'argent|économies|héritage'],
    ['Les bijoux', 14, 'bijoux|bijou|bague'],
    ['Les yeux', 11, 'couleur des yeux|le physique|la ressemblance'],
    ['Les meubles', 9, 'meuble|mobilier'],
    ['Le caractère', 8, 'traits de caractère|personnalité'],
    ['Les photos', 6, 'photos de famille|souvenirs'],
    ['La voiture', 4, 'voiture'],
  ]),
  Q('Citez un prénom que l’on entend souvent chez les personnes âgées.', 'difficile', [
    ['Marie', 30, ''],
    ['Jean', 25, ''],
    ['Louis', 12, ''],
    ['Pierre', 10, ''],
    ['Jeanne', 8, ''],
    ['Joseph', 7, ''],
    ['Marguerite', 5, ''],
    ['Germaine', 3, ''],
  ]),
];
