const Q = require('./_q')('France');
module.exports = [
  Q('Citez un monument de Paris.', 'facile', [
    ['La tour Eiffel', 46, 'tour eiffel'],
    ['L’Arc de Triomphe', 18, 'arc de triomphe'],
    ['Notre-Dame', 16, 'notre dame|notre dame de paris'],
    ['Le Louvre', 12, 'louvre|pyramide du louvre'],
    ['Le Sacré-Cœur', 8, 'sacré coeur|sacré cœur|montmartre'],
  ]),
  Q('Citez un fromage français.', 'facile', [
    ['Camembert', 34, ''],
    ['Comté', 20, ''],
    ['Roquefort', 18, ''],
    ['Brie', 16, 'brie de meaux'],
    ['Reblochon', 12, ''],
  ]),
  Q('Citez un symbole de la France.', 'facile', [
    ['Le drapeau tricolore', 30, 'drapeau|bleu blanc rouge'],
    ['Le coq', 26, 'coq'],
    ['Marianne', 18, ''],
    ['La tour Eiffel', 14, 'tour eiffel'],
    ['La baguette', 12, 'baguette|pain'],
  ]),
  Q('Citez une région française.', 'moyen', [
    ['Bretagne', 28, ''],
    ['Normandie', 20, ''],
    ['Provence', 16, 'provence alpes côte d azur|paca'],
    ['Alsace', 14, 'grand est'],
    ['Occitanie', 12, ''],
    ['Corse', 10, ''],
  ]),
  Q('Citez une spécialité culinaire d’une région française.', 'moyen', [
    ['La choucroute', 24, 'choucroute'],
    ['Les crêpes', 22, 'crêpes|galettes|crêpe'],
    ['La bouillabaisse', 16, 'bouillabaisse'],
    ['La tartiflette', 16, 'tartiflette'],
    ['Le cassoulet', 12, 'cassoulet'],
    ['La quiche lorraine', 10, 'quiche'],
  ]),
  Q('Citez un fleuve français.', 'moyen', [
    ['La Seine', 34, 'seine'],
    ['La Loire', 28, 'loire'],
    ['Le Rhône', 20, 'rhône|rhone'],
    ['La Garonne', 14, 'garonne'],
    ['Le Rhin', 4, 'rhin'],
  ]),
  Q('Citez un président de la Ve République.', 'difficile', [
    ['Emmanuel Macron', 26, 'macron'],
    ['Charles de Gaulle', 20, 'de gaulle|gaulle'],
    ['Jacques Chirac', 16, 'chirac'],
    ['François Mitterrand', 14, 'mitterrand'],
    ['Nicolas Sarkozy', 10, 'sarkozy|sarko'],
    ['François Hollande', 8, 'hollande'],
    ['Valéry Giscard d’Estaing', 4, 'giscard|vge'],
    ['Georges Pompidou', 2, 'pompidou'],
  ]),
  Q('Citez une chose que les touristes trouvent typiquement française.', 'difficile', [
    ['Le béret', 22, 'béret'],
    ['La baguette', 20, 'baguette|pain'],
    ['Le vin', 16, 'vin|vin rouge'],
    ['Les croissants', 13, 'croissant'],
    ['Le fromage', 11, 'fromage'],
    ['Les grèves', 8, 'grève'],
    ['La marinière', 6, 'marinière|rayures'],
    ['Les escargots', 4, 'escargot'],
  ]),
];
