const Q = require('./_q')('Jeux vidéo');
module.exports = [
  Q('Citez une console de jeux vidéo.', 'facile', [
    ['PlayStation', 36, 'ps5|ps4|play station|play'],
    ['Nintendo Switch', 24, 'switch'],
    ['Xbox', 18, ''],
    ['Game Boy', 12, 'gameboy'],
    ['Wii', 10, ''],
  ]),
  Q('Citez un personnage de jeu vidéo.', 'facile', [
    ['Mario', 40, 'super mario'],
    ['Pikachu', 18, ''],
    ['Sonic', 16, ''],
    ['Link', 14, 'zelda'],
    ['Lara Croft', 12, 'lara'],
  ]),
  Q('Citez un objet que l’on utilise pour jouer aux jeux vidéo.', 'facile', [
    ['Une manette', 44, 'manette|joystick'],
    ['Un casque', 18, 'casque|casque audio'],
    ['Un clavier', 16, 'clavier'],
    ['Une souris', 14, 'souris'],
    ['Un écran', 8, 'écran|télé'],
  ]),
  Q('Citez une raison de se fâcher en jouant aux jeux vidéo.', 'moyen', [
    ['Perdre', 34, 'défaite|perdre la partie'],
    ['La connexion qui lag', 20, 'lag|connexion|bug|internet'],
    ['Un tricheur', 14, 'triche|tricheurs'],
    ['Un coéquipier nul', 12, 'coéquipier|équipe nulle'],
    ['Pas de sauvegarde', 10, 'sauvegarde|perdre sa sauvegarde'],
    ['On doit arrêter de jouer', 10, 'arrêter|il faut aller manger|parents'],
  ]),
  Q('Citez un jeu vidéo de sport.', 'moyen', [
    ['FIFA', 38, 'ea sports fc|fc 25'],
    ['NBA 2K', 18, 'nba|2k'],
    ['Mario Kart', 16, 'mario kart'],
    ['Rocket League', 12, ''],
    ['Wii Sports', 9, ''],
    ['Gran Turismo', 7, ''],
  ]),
  Q('Citez un Pokémon.', 'moyen', [
    ['Pikachu', 44, ''],
    ['Dracaufeu', 16, ''],
    ['Salamèche', 12, ''],
    ['Bulbizarre', 10, ''],
    ['Rondoudou', 10, ''],
    ['Mew', 8, 'mewtwo'],
  ]),
  Q('Citez un jeu vidéo auquel on joue en famille.', 'difficile', [
    ['Mario Kart', 34, ''],
    ['Just Dance', 18, ''],
    ['Mario Party', 14, ''],
    ['Wii Sports', 10, ''],
    ['Minecraft', 8, ''],
    ['Animal Crossing', 7, ''],
    ['Super Smash Bros', 5, 'smash|smash bros'],
    ['Overcooked', 4, ''],
  ]),
  Q('Citez quelque chose que l’on trouve souvent dans un jeu vidéo.', 'difficile', [
    ['Des vies', 26, 'vie|points de vie|cœurs'],
    ['Des niveaux', 20, 'niveau|level|levels'],
    ['Un boss', 16, 'boss|boss final'],
    ['Des pièces', 12, 'pièce|argent|or'],
    ['Des armes', 10, 'arme|épée'],
    ['Des quêtes', 7, 'quête|mission|missions'],
    ['Un trésor', 5, 'coffre'],
    ['Un game over', 4, 'game over|perdu'],
  ]),
  Q('Citez un jeu vidéo qui fait peur.', 'difficile', [
    ['Resident Evil', 30, 'resident'],
    ['Five Nights at Freddy’s', 20, 'fnaf|five nights at freddy s'],
    ['Silent Hill', 14, ''],
    ['Outlast', 10, ''],
    ['Alien Isolation', 9, 'alien'],
    ['Dead Space', 7, ''],
    ['Amnesia', 6, ''],
    ['Phasmophobia', 4, 'phasmo'],
  ]),
];
