const Q = require('./_q')('Musique');
module.exports = [
  Q('Citez un style de musique.', 'facile', [
    ['Rock', 28, ''],
    ['Rap', 24, 'hip hop|hip-hop'],
    ['Pop', 20, ''],
    ['Jazz', 14, ''],
    ['Musique classique', 14, 'classique'],
  ]),
  Q('Citez un chanteur ou une chanteuse français célèbre.', 'facile', [
    ['Johnny Hallyday', 30, 'johnny|hallyday'],
    ['Édith Piaf', 22, 'piaf'],
    ['Céline Dion', 18, 'céline'],
    ['Jean-Jacques Goldman', 16, 'goldman'],
    ['Aya Nakamura', 14, 'aya'],
  ]),
  Q('Citez une chanson que l’on chante aux enfants.', 'facile', [
    ['Frère Jacques', 28, 'frère jacques'],
    ['Au clair de la lune', 24, 'clair de la lune'],
    ['Joyeux anniversaire', 18, 'joyeux anniversaire|bon anniversaire'],
    ['Une souris verte', 16, 'souris verte'],
    ['Petit papa Noël', 14, 'petit papa noël'],
  ]),
  Q('Citez un endroit où l’on écoute de la musique.', 'moyen', [
    ['En voiture', 32, 'voiture'],
    ['Dans un concert', 24, 'concert|salle de concert'],
    ['À la maison', 16, 'maison|chez soi'],
    ['Sous la douche', 12, 'douche'],
    ['En boîte de nuit', 10, 'boîte|discothèque|club'],
    ['Dans les transports', 6, 'métro|bus|train'],
  ]),
  Q('Citez un instrument de musique que l’on joue avec la bouche.', 'moyen', [
    ['Flûte', 32, 'flûte à bec|flûte traversière'],
    ['Trompette', 22, ''],
    ['Saxophone', 18, 'saxo'],
    ['Harmonica', 14, ''],
    ['Clarinette', 9, ''],
    ['Trombone', 5, ''],
  ]),
  Q('Citez quelque chose que l’on fait à un concert.', 'moyen', [
    ['Chanter', 30, 'chanter avec'],
    ['Danser', 24, 'bouger|sauter'],
    ['Filmer', 16, 'vidéos|faire des vidéos|photos|prendre des photos'],
    ['Applaudir', 14, 'applaudissements'],
    ['Crier', 10, 'hurler'],
    ['Boire un verre', 6, 'bière|boire'],
  ]),
  Q('Citez un groupe ou artiste international célèbre.', 'difficile', [
    ['Les Beatles', 26, 'beatles'],
    ['Michael Jackson', 24, 'jackson'],
    ['Queen', 14, 'freddie mercury'],
    ['Madonna', 10, ''],
    ['Taylor Swift', 9, 'swift'],
    ['ABBA', 7, ''],
    ['Elvis Presley', 6, 'elvis|presley'],
    ['Beyoncé', 4, 'beyonce'],
  ]),
  Q('Citez une chanson que l’on entend dans toutes les fêtes.', 'difficile', [
    ['La macarena', 22, 'macarena'],
    ['Les sardines', 20, 'sardines|patrick sébastien'],
    ['Joe le taxi', 12, 'joe le taxi'],
    ['La danse des canards', 12, 'danse des canards|canards'],
    ['Alexandrie Alexandra', 11, 'alexandrie|alexandra'],
    ['Je veux', 9, 'zaz'],
    ['YMCA', 8, 'village people'],
    ['Despacito', 6, ''],
  ]),
  Q('Citez une chose que fait un DJ.', 'difficile', [
    ['Mixer', 34, 'mix|mixage|mélanger les morceaux'],
    ['Passer des disques', 20, 'disques|vinyles|passer de la musique'],
    ['Mettre l’ambiance', 16, 'ambiance|chauffer la salle'],
    ['Porter un casque', 10, 'casque'],
    ['Lever les bras', 8, 'bras en l’air'],
    ['Prendre des demandes', 6, 'demandes|dédicaces'],
    ['Monter le son', 4, 'volume|monter le volume'],
    ['Faire des scratchs', 2, 'scratch|scratcher'],
  ]),
];
