const Q = require('./_q')('Nourriture');
module.exports = [
  Q('Citez un fruit.', 'facile', [
    ['Pomme', 35, ''],
    ['Banane', 22, ''],
    ['Fraise', 16, ''],
    ['Orange', 15, 'clémentine|mandarine'],
    ['Poire', 12, ''],
  ]),
  Q('Citez un légume.', 'facile', [
    ['Carotte', 32, ''],
    ['Tomate', 22, ''],
    ['Haricot vert', 16, 'haricots|haricot'],
    ['Courgette', 15, ''],
    ['Pomme de terre', 15, 'patate|patates'],
  ]),
  Q('Citez quelque chose que l’on met sur une pizza.', 'facile', [
    ['Fromage', 34, 'mozzarella|emmental|gruyère'],
    ['Jambon', 22, ''],
    ['Sauce tomate', 18, 'tomate|tomates'],
    ['Champignons', 15, 'champignon'],
    ['Olives', 11, 'olive'],
  ]),
  Q('Citez quelque chose que l’on mange au petit-déjeuner.', 'facile', [
    ['Tartines', 30, 'pain|tartine|pain beurre|tartine beurrée'],
    ['Céréales', 26, 'céréale|muesli|flocons d’avoine'],
    ['Croissant', 20, 'viennoiserie|pain au chocolat|chocolatine'],
    ['Yaourt', 13, 'yaourts|fromage blanc'],
    ['Fruit', 11, 'fruits|banane|pomme'],
  ]),
  Q('Citez quelque chose que l’on fait griller au barbecue.', 'moyen', [
    ['Saucisses', 34, 'saucisse|merguez|chipolata|chipolatas'],
    ['Côtelettes', 20, 'côtelette|côtes d’agneau|côtes de porc'],
    ['Brochettes', 16, 'brochette'],
    ['Steak', 13, 'bœuf|steaks|entrecôte'],
    ['Poulet', 10, 'cuisses de poulet|ailes de poulet'],
    ['Légumes', 7, 'poivrons|courgettes|maïs'],
  ]),
  Q('Citez un dessert.', 'moyen', [
    ['Gâteau au chocolat', 28, 'gâteau|fondant au chocolat|moelleux au chocolat'],
    ['Tarte', 22, 'tarte aux pommes|tarte au citron|tarte aux fraises'],
    ['Crème brûlée', 15, 'crème|crème caramel'],
    ['Mousse au chocolat', 14, 'mousse'],
    ['Glace', 12, 'glaces|sorbet'],
    ['Tiramisu', 9, ''],
  ]),
  Q('Citez une boisson chaude.', 'moyen', [
    ['Café', 42, 'expresso|espresso|cappuccino'],
    ['Thé', 28, 'tisane|infusion'],
    ['Chocolat chaud', 20, 'chocolat|cacao'],
    ['Vin chaud', 5, ''],
    ['Soupe', 5, 'potage|bouillon'],
  ]),
  Q('Citez un ingrédient indispensable pour faire une crêpe.', 'moyen', [
    ['Farine', 34, ''],
    ['Œufs', 28, 'oeuf|oeufs'],
    ['Lait', 24, ''],
    ['Sucre', 7, ''],
    ['Beurre', 4, 'huile'],
    ['Sel', 3, 'pincée de sel'],
  ]),
  Q('Citez un aliment que les enfants n’aiment pas.', 'difficile', [
    ['Épinards', 30, 'épinard'],
    ['Brocolis', 18, 'brocoli'],
    ['Choux de Bruxelles', 15, 'chou de bruxelles|choux|chou'],
    ['Poisson', 11, ''],
    ['Endives', 9, 'endive|chicon'],
    ['Haricots verts', 7, 'haricot vert|haricots'],
    ['Foie', 6, 'foie de veau'],
    ['Navets', 4, 'navet'],
  ]),
];
