const Q = require('./_q')('Relations');
module.exports = [
  Q('Citez une qualité que l’on cherche chez son partenaire.', 'facile', [
    ['L’humour', 32, 'humour|drôle|marrant'],
    ['La gentillesse', 24, 'gentil|gentille|bienveillance'],
    ['La fidélité', 20, 'fidèle'],
    ['L’honnêteté', 14, 'honnête|sincérité|franchise'],
    ['La beauté', 10, 'beau|belle|physique'],
  ]),
  Q('Citez un cadeau pour la Saint-Valentin.', 'facile', [
    ['Des fleurs', 34, 'fleurs|bouquet|roses|rose'],
    ['Du chocolat', 22, 'chocolats|bonbons'],
    ['Un bijou', 20, 'bijoux|bague|collier'],
    ['Un dîner au restaurant', 14, 'restaurant|dîner|resto'],
    ['Du parfum', 10, 'parfum'],
  ]),
  Q('Citez quelque chose que l’on fait avec ses amis.', 'facile', [
    ['Boire un verre', 28, 'apéro|verre|aller au bar'],
    ['Manger ensemble', 22, 'restaurant|dîner|repas'],
    ['Discuter', 18, 'parler|papoter'],
    ['Faire la fête', 18, 'soirée|fête|sortir'],
    ['Jouer', 14, 'jeux|jeux de société|jeux vidéo'],
  ]),
  Q('Citez un motif de dispute dans un couple.', 'moyen', [
    ['L’argent', 26, 'argent|dépenses'],
    ['Les tâches ménagères', 22, 'ménage|vaisselle|tâches'],
    ['La jalousie', 16, 'jaloux|jalouse'],
    ['La belle-famille', 14, 'belle famille|belle mère|beaux parents'],
    ['Le téléphone', 12, 'écrans'],
    ['Les enfants', 10, 'éducation des enfants'],
  ]),
  Q('Citez une façon de dire « je t’aime » sans parler.', 'moyen', [
    ['Un bisou', 30, 'bisou|baiser|embrasser|bisous'],
    ['Un câlin', 26, 'câlin|câlins|serrer dans ses bras'],
    ['Un cadeau', 14, 'cadeau|offrir'],
    ['Un sourire', 12, 'sourire'],
    ['Tenir la main', 10, 'main|se tenir la main'],
    ['Un petit mot', 8, 'lettre|message|mot doux'],
  ]),
  Q('Citez un endroit où l’on peut rencontrer l’amour.', 'moyen', [
    ['Sur une application', 28, 'application|appli|internet|site de rencontre|tinder'],
    ['Au travail', 22, 'travail|bureau'],
    ['En soirée', 18, 'soirée|fête|bar|boîte de nuit'],
    ['Chez des amis', 14, 'amis|par des amis'],
    ['À l’école', 10, 'école|fac|université|lycée'],
    ['En vacances', 8, 'vacances'],
  ]),
  Q('Citez une chose que l’on fait pour un anniversaire de mariage.', 'difficile', [
    ['Un dîner romantique', 32, 'restaurant|dîner|resto'],
    ['Offrir un cadeau', 22, 'cadeau|cadeaux'],
    ['Partir en week-end', 16, 'week-end|week end|voyage|escapade'],
    ['Offrir des fleurs', 12, 'fleurs|bouquet'],
    ['Faire une fête', 7, 'fête|réception'],
    ['Regarder les photos', 5, 'photos|album'],
    ['Renouveler ses vœux', 4, 'vœux|voeux'],
    ['Écrire une lettre', 2, 'lettre|carte'],
  ]),
  Q('Citez quelque chose qui rend un premier rendez-vous gênant.', 'difficile', [
    ['Les blancs', 26, 'silence|silences|blanc|rien à dire'],
    ['Être en retard', 18, 'retard'],
    ['Parler de son ex', 15, 'ex|son ex'],
    ['Regarder son téléphone', 12, 'téléphone'],
    ['L’addition', 10, 'addition|payer|qui paye'],
    ['Une tache sur ses vêtements', 7, 'tache|renverser|renverser son verre'],
    ['La mauvaise haleine', 7, 'haleine|mauvais souffle'],
    ['Croiser quelqu’un qu’on connaît', 5, 'croiser quelqu’un|rencontrer quelqu’un'],
  ]),
  Q('Citez une chose qu’un bon ami fait pour vous.', 'difficile', [
    ['Il vous écoute', 30, 'écoute|écouter'],
    ['Il vous aide', 22, 'aide|aider|rendre service'],
    ['Il vous fait rire', 14, 'rire|faire rire'],
    ['Il garde vos secrets', 12, 'secrets|secret'],
    ['Il est là quand ça va mal', 10, 'présent|être là|soutien|soutenir'],
    ['Il vous aide à déménager', 6, 'déménager|déménagement'],
    ['Il se souvient de votre anniversaire', 4, 'anniversaire'],
    ['Il vous dit la vérité', 2, 'vérité|franchise'],
  ]),
];
