const Q = require('./_q')('Sport');
module.exports = [
  Q('Citez un sport qui se joue avec un ballon.', 'facile', [
    ['Football', 40, ''],
    ['Basket', 20, 'basketball|basket ball'],
    ['Rugby', 16, ''],
    ['Handball', 14, 'hand'],
    ['Volley', 10, 'volleyball|volley ball'],
  ]),
  Q('Citez un sport que l’on pratique dans l’eau.', 'facile', [
    ['Natation', 42, 'nager|nage'],
    ['Water-polo', 16, 'water polo|waterpolo'],
    ['Surf', 15, ''],
    ['Plongée', 14, 'plongée sous marine'],
    ['Aquagym', 13, 'aqua gym|aquabike'],
  ]),
  Q('Citez un sport d’hiver.', 'facile', [
    ['Ski', 48, 'ski alpin|skier'],
    ['Snowboard', 20, 'surf des neiges'],
    ['Patin à glace', 16, 'patinage|patins'],
    ['Luge', 10, ''],
    ['Hockey sur glace', 6, 'hockey'],
  ]),
  Q('Citez quelque chose que l’on emporte à la salle de sport.', 'moyen', [
    ['Une bouteille d’eau', 30, 'eau|gourde|bouteille'],
    ['Une serviette', 26, 'serviette'],
    ['Des baskets', 18, 'baskets|chaussures|tennis'],
    ['Des écouteurs', 12, 'écouteurs|casque|musique'],
    ['Un cadenas', 8, 'cadenas'],
    ['Un gel douche', 6, 'gel douche|savon'],
  ]),
  Q('Citez un sportif français célèbre.', 'moyen', [
    ['Zinédine Zidane', 30, 'zidane|zizou'],
    ['Kylian Mbappé', 26, 'mbappé|mbappe'],
    ['Teddy Riner', 14, 'riner'],
    ['Antoine Dupont', 12, 'dupont'],
    ['Tony Parker', 10, 'parker'],
    ['Léon Marchand', 8, 'marchand'],
  ]),
  Q('Citez un sport que l’on voit aux Jeux olympiques.', 'moyen', [
    ['Athlétisme', 32, 'course|course à pied|sprint|100 mètres'],
    ['Natation', 24, 'nage'],
    ['Gymnastique', 16, 'gym'],
    ['Judo', 12, ''],
    ['Escrime', 9, ''],
    ['Cyclisme', 7, 'vélo|bmx'],
  ]),
  Q('Citez une raison d’arrêter le sport.', 'difficile', [
    ['Une blessure', 34, 'blessure|blessé|se blesser'],
    ['Le manque de temps', 22, 'temps|pas le temps'],
    ['La flemme', 16, 'paresse|motivation|plus de motivation'],
    ['Le prix', 10, 'trop cher|argent|abonnement'],
    ['Le travail', 7, 'boulot'],
    ['Les enfants', 5, 'naissance|bébé'],
    ['La fatigue', 4, 'fatigué'],
    ['Le mauvais temps', 2, 'pluie|froid'],
  ]),
  Q('Citez un équipement de football.', 'difficile', [
    ['Ballon', 30, ''],
    ['Crampons', 22, 'chaussures|chaussures à crampons'],
    ['Maillot', 14, 'tenue'],
    ['Protège-tibias', 12, 'protège tibias|jambières'],
    ['Cages', 9, 'buts|cage|filet'],
    ['Gants de gardien', 6, 'gants'],
    ['Short', 4, ''],
    ['Sifflet', 3, ''],
  ]),
  Q('Citez une chose que fait un supporter pendant un match.', 'difficile', [
    ['Crier', 30, 'hurler|encourager|crier fort'],
    ['Chanter', 20, 'chants|chanson'],
    ['Agiter un drapeau', 14, 'drapeau|écharpe|agiter son écharpe'],
    ['Applaudir', 12, 'applaudissements'],
    ['Insulter l’arbitre', 10, 'arbitre|siffler|huer'],
    ['Boire une bière', 7, 'bière|boire'],
    ['Se maquiller', 4, 'maquillage|peinture sur le visage'],
    ['Faire la ola', 3, 'ola'],
  ]),
];
