const Q = require('./_q')('Technologie');
module.exports = [
  Q('Citez un appareil électronique que l’on a à la maison.', 'facile', [
    ['Télévision', 34, ''],
    ['Ordinateur', 24, ''],
    ['Téléphone', 18, ''],
    ['Tablette', 12, 'ipad'],
    ['Console de jeux', 12, 'console|playstation|ps5|switch|xbox'],
  ]),
  Q('Citez une marque de téléphone.', 'facile', [
    ['Apple', 40, 'iphone'],
    ['Samsung', 30, 'galaxy'],
    ['Xiaomi', 12, ''],
    ['Google', 10, 'pixel'],
    ['Huawei', 8, ''],
  ]),
  Q('Citez un réseau social.', 'facile', [
    ['Facebook', 28, 'fb'],
    ['Instagram', 26, 'insta'],
    ['TikTok', 22, 'tik tok'],
    ['Snapchat', 14, 'snap'],
    ['X', 10, 'twitter'],
  ]),
  Q('Citez une chose qui énerve avec un téléphone.', 'moyen', [
    ['La batterie vide', 36, 'batterie|plus de batterie|batterie faible'],
    ['Pas de réseau', 22, 'réseau|pas de connexion|wifi'],
    ['L’écran cassé', 16, 'écran|écran fissuré'],
    ['Les publicités', 10, 'pub|pubs|publicité'],
    ['Les mises à jour', 9, 'mise à jour|màj'],
    ['Plus de place', 7, 'mémoire pleine|stockage'],
  ]),
  Q('Citez quelque chose que l’on fait sur Internet.', 'moyen', [
    ['Regarder des vidéos', 28, 'vidéos|youtube|streaming|séries'],
    ['Aller sur les réseaux sociaux', 22, 'réseaux sociaux|facebook|instagram'],
    ['Faire des achats', 18, 'acheter|shopping|achats en ligne'],
    ['Lire ses mails', 14, 'mails|emails|mail|e-mails'],
    ['Faire des recherches', 10, 'chercher|google|rechercher'],
    ['Jouer', 8, 'jeux en ligne|jeux'],
  ]),
  Q('Citez un objet qui fonctionne avec des piles.', 'moyen', [
    ['La télécommande', 40, 'télécommande'],
    ['Un jouet', 18, 'jouets'],
    ['Une lampe de poche', 14, 'lampe|lampe torche|torche'],
    ['Une horloge', 12, 'pendule|réveil|montre'],
    ['Une calculatrice', 9, 'calculette'],
    ['Une souris', 7, 'souris sans fil'],
  ]),
  Q('Citez une invention qui a changé le monde.', 'difficile', [
    ['Internet', 26, 'le web'],
    ['L’électricité', 20, 'électricité|ampoule|lampe'],
    ['La roue', 15, 'roue'],
    ['Le téléphone', 12, ''],
    ['La voiture', 9, 'automobile'],
    ['L’imprimerie', 8, 'imprimerie|livre'],
    ['L’avion', 6, 'avion'],
    ['Le feu', 4, 'feu'],
  ]),
  Q('Citez quelque chose que l’on peut demander à un assistant vocal.', 'difficile', [
    ['La météo', 32, 'météo|le temps qu’il fait'],
    ['Mettre de la musique', 24, 'musique|une chanson'],
    ['L’heure', 12, 'heure'],
    ['Mettre un réveil', 10, 'réveil|alarme|minuteur'],
    ['Appeler quelqu’un', 8, 'appeler|téléphoner'],
    ['Une recette', 6, 'recette'],
    ['Allumer la lumière', 5, 'lumière|lampe'],
    ['Une blague', 3, 'blagues|raconter une blague'],
  ]),
  Q('Citez un mot de passe trop facile.', 'difficile', [
    ['123456', 36, '1234|12345|123456789'],
    ['Password', 18, 'mot de passe|motdepasse'],
    ['Sa date de naissance', 14, 'date de naissance|anniversaire'],
    ['Son prénom', 10, 'prénom|nom'],
    ['Azerty', 9, 'qwerty'],
    ['Le nom de son animal', 6, 'animal|nom du chien|nom du chat'],
    ['0000', 4, ''],
    ['Soleil', 3, ''],
  ]),
];
