const Q = require('./_q')('Travail');
module.exports = [
  Q('Citez un métier que les enfants rêvent de faire.', 'facile', [
    ['Pompier', 28, 'sapeur pompier'],
    ['Footballeur', 22, 'joueur de foot|foot'],
    ['Vétérinaire', 18, 'véto'],
    ['Astronaute', 16, 'cosmonaute|spationaute'],
    ['Policier', 16, 'policière|police|gendarme'],
  ]),
  Q('Citez un objet que l’on trouve sur un bureau.', 'facile', [
    ['Ordinateur', 34, 'écran|ordinateur portable'],
    ['Stylo', 24, 'crayon|stylos'],
    ['Agrafeuse', 14, ''],
    ['Téléphone', 14, 'poste'],
    ['Papiers', 14, 'feuilles|dossiers|papier'],
  ]),
  Q('Citez une chose que l’on fait pendant la pause au travail.', 'facile', [
    ['Boire un café', 42, 'café|machine à café'],
    ['Discuter avec les collègues', 22, 'discuter|parler|bavarder|collègues'],
    ['Fumer une cigarette', 16, 'fumer|cigarette|clope'],
    ['Regarder son téléphone', 12, 'téléphone|réseaux sociaux'],
    ['Manger', 8, 'grignoter|goûter|en-cas'],
  ]),
  Q('Citez un métier où l’on travaille la nuit.', 'moyen', [
    ['Infirmier', 26, 'infirmière|soignant|aide soignant'],
    ['Boulanger', 20, 'boulangère'],
    ['Policier', 16, 'police|gendarme'],
    ['Médecin', 14, 'urgentiste|docteur'],
    ['Vigile', 12, 'gardien|agent de sécurité|veilleur de nuit'],
    ['Chauffeur de taxi', 12, 'taxi|chauffeur'],
  ]),
  Q('Citez quelque chose que l’on fait lors d’un entretien d’embauche.', 'moyen', [
    ['Se présenter', 30, 'présentation|parler de soi'],
    ['Serrer la main', 22, 'poignée de main|serrer la main du recruteur'],
    ['Parler de ses qualités', 16, 'qualités|défauts|ses défauts'],
    ['Montrer son CV', 14, 'cv|curriculum'],
    ['Poser des questions', 10, 'questions'],
    ['Parler du salaire', 8, 'salaire|rémunération'],
  ]),
  Q('Citez ce qui rend un collègue insupportable.', 'moyen', [
    ['Il parle trop', 28, 'bavard|trop bavard|parle trop'],
    ['Il est toujours en retard', 18, 'retard|en retard'],
    ['Il se plaint tout le temps', 16, 'se plaint|râleur|plaintes'],
    ['Il ne travaille pas', 15, 'fainéant|paresseux|feignant'],
    ['Il vole les idées', 12, 'vol des idées|s’attribue le travail'],
    ['Il mange bruyamment', 11, 'mange fort|bruit en mangeant'],
  ]),
  Q('Citez un avantage que l’on aimerait avoir au travail.', 'difficile', [
    ['Une augmentation', 30, 'augmentation|salaire|meilleur salaire|prime'],
    ['Plus de vacances', 22, 'vacances|congés|jours de congé'],
    ['Le télétravail', 15, 'télétravail|travail à domicile'],
    ['Une voiture de fonction', 10, 'voiture|voiture de société'],
    ['Des tickets restaurant', 9, 'tickets resto|cantine|chèques déjeuner'],
    ['Des horaires flexibles', 7, 'horaires|flexibilité|semaine de 4 jours'],
    ['Une salle de sport', 4, 'sport|salle de gym'],
    ['Un baby-foot', 3, 'baby foot|babyfoot'],
  ]),
  Q('Citez un métier qui demande de porter un uniforme.', 'difficile', [
    ['Policier', 28, 'police|gendarme'],
    ['Pompier', 20, ''],
    ['Militaire', 15, 'soldat|armée'],
    ['Infirmier', 12, 'infirmière|médecin|hôpital'],
    ['Pilote', 9, 'pilote d’avion|hôtesse de l’air|steward'],
    ['Cuisinier', 7, 'chef|cuisinière'],
    ['Facteur', 5, 'postier'],
    ['Juge', 4, 'avocat|magistrat'],
  ]),
  Q('Citez une excuse pour ne pas aller au travail.', 'difficile', [
    ['Être malade', 40, 'malade|maladie|grippe|rhume|fièvre'],
    ['Un enfant malade', 16, 'enfant|les enfants'],
    ['Une panne de voiture', 12, 'panne|voiture'],
    ['Un rendez-vous médical', 10, 'rendez-vous|médecin|dentiste'],
    ['Une grève', 8, 'grève|pas de transport'],
    ['Un décès dans la famille', 6, 'décès|enterrement'],
    ['Une fuite d’eau', 5, 'dégât des eaux|fuite|plombier'],
    ['La neige', 3, 'neige|météo'],
  ]),
];
