const Q = require('./_q')('Vacances');
module.exports = [
  Q('Citez quelque chose que l’on emporte à la plage.', 'facile', [
    ['Serviette', 32, 'serviette de plage|drap de bain'],
    ['Crème solaire', 26, 'crème|écran total|protection solaire'],
    ['Parasol', 16, ''],
    ['Maillot de bain', 14, 'maillot'],
    ['Lunettes de soleil', 12, 'lunettes'],
  ]),
  Q('Citez une destination de vacances en France.', 'facile', [
    ['La Côte d’Azur', 26, 'côte d azur|nice|cannes|saint tropez'],
    ['La Bretagne', 24, 'bretagne'],
    ['Les Alpes', 18, 'alpes|montagne|la montagne'],
    ['Paris', 16, ''],
    ['La Corse', 16, 'corse'],
  ]),
  Q('Citez une activité que l’on fait en vacances.', 'facile', [
    ['Se baigner', 30, 'nager|baignade|piscine|mer'],
    ['Visiter', 22, 'visites|tourisme|musées|monuments'],
    ['Bronzer', 20, 'bronzette|soleil|lézarder'],
    ['Randonner', 15, 'randonnée|rando|marcher'],
    ['Dormir', 13, 'se reposer|repos|sieste'],
  ]),
  Q('Citez un moyen de transport pour partir en vacances.', 'facile', [
    ['Voiture', 40, ''],
    ['Avion', 30, ''],
    ['Train', 18, 'tgv'],
    ['Bateau', 7, 'ferry|croisière'],
    ['Camping-car', 5, 'camping car|caravane|van'],
  ]),
  Q('Citez quelque chose que l’on achète en souvenir de vacances.', 'moyen', [
    ['Des cartes postales', 28, 'carte postale|cartes'],
    ['Un magnet', 22, 'magnets|aimant|aimant de frigo'],
    ['Un tee-shirt', 15, 't-shirt|tshirt|tee shirt'],
    ['Des spécialités locales', 14, 'nourriture|spécialités|produits locaux'],
    ['Un porte-clés', 12, 'porte clés|porte-clef'],
    ['Une boule à neige', 9, 'boule de neige'],
  ]),
  Q('Citez un endroit où l’on dort en vacances.', 'moyen', [
    ['À l’hôtel', 34, 'hôtel'],
    ['Au camping', 24, 'camping|tente'],
    ['Une location', 18, 'location|airbnb|gîte|appartement'],
    ['Chez la famille', 12, 'famille|chez des amis|amis'],
    ['Un mobil-home', 7, 'mobil home|mobilhome'],
    ['Une chambre d’hôtes', 5, 'chambre d hôte'],
  ]),
  Q('Citez un problème qui peut gâcher des vacances.', 'moyen', [
    ['La pluie', 30, 'mauvais temps|pluie|orage'],
    ['Tomber malade', 18, 'malade|maladie|intoxication'],
    ['Les moustiques', 14, 'moustique|piqûres'],
    ['Perdre ses bagages', 14, 'valise perdue|bagages|perdre sa valise'],
    ['Un coup de soleil', 12, 'coup de soleil|insolation'],
    ['Les disputes', 12, 'dispute|se disputer'],
  ]),
  Q('Citez un pays où les Français aiment partir en vacances.', 'difficile', [
    ['Espagne', 32, ''],
    ['Italie', 22, ''],
    ['Portugal', 14, ''],
    ['Grèce', 10, ''],
    ['Maroc', 8, ''],
    ['États-Unis', 6, 'usa|amérique|etats unis'],
    ['Croatie', 5, ''],
    ['Thaïlande', 3, ''],
  ]),
  Q('Citez quelque chose que l’on fait la veille d’un départ en vacances.', 'difficile', [
    ['Faire sa valise', 40, 'valise|bagages|faire ses bagages'],
    ['Vérifier ses papiers', 14, 'papiers|passeport|billets'],
    ['Faire le ménage', 12, 'ménage|ranger la maison'],
    ['Vider le frigo', 9, 'frigo'],
    ['Faire le plein', 8, 'essence|plein d’essence'],
    ['Arroser les plantes', 7, 'plantes|faire garder les plantes'],
    ['Faire garder les animaux', 6, 'animaux|chat|chien'],
    ['Mal dormir', 4, 'stresser|stress'],
  ]),
];
