const mk = require('./_choice');
const Q = (p, ...opts) => ({ p, options: opts.map(t => ({ t })) });
module.exports = mk({
  id: 'choixgroupe', category: 'Humour', name: 'Le choix du groupe', rounds: 5, points: 200, mode: 'majority', title: 'Votre choix', categories: ['Humour', 'Vie quotidienne', 'Absurde'],
  desc: 'Des options absurdes : gagnez des points en votant comme la majorité.',
  questions: [
    Q('Vous devez adopter un nouvel animal de compagnie :', 'Un pigeon qui juge tout le monde', 'Un hamster géant', 'Un perroquet qui répète vos secrets', 'Un escargot ultra rapide'),
    Q('Quel super-pouvoir inutile choisir ?', 'Parler aux fourmis', 'Savoir quand quelqu\'un va éternuer', 'Faire apparaître un cornichon', 'Toujours connaître l\'heure exacte'),
    Q('Le nouveau plat national obligatoire :', 'Pizza à l\'ananas', 'Soupe de chocolat', 'Spaghettis au ketchup', 'Fromage glacé'),
    Q('Un seul objet pour une île déserte :', 'Un trampoline', 'Un piano sans touches', 'Un parapluie géant', 'Un GPS qui marche à l\'envers'),
    Q('La pire chose à entendre au réveil :', '« On a rendez-vous avec ta belle-mère »', '« Il n\'y a plus de café »', '« Le chat a mangé tes clés »', '« Aujourd\'hui, c\'est encore lundi »'),
    Q('Un métier devient obligatoire un jour par an pour tout le monde :', 'Boulanger', 'Clown', 'Éboueur', 'Pilote d\'avion'),
    Q('Vous devez vivre une semaine dans :', 'Un château hanté', 'Un sous-marin', 'Une cabane dans un arbre', 'Un supermarché fermé'),
    Q('Votre colocataire idéal :', 'Un pirate à la retraite', 'Un robot ménager qui parle', 'Une mamie qui cuisine', 'Un chat qui paie le loyer'),
    Q('Pour le reste de votre vie, vous ne pouvez manger que :', 'Des pâtes', 'Des frites', 'Du fromage', 'Des crêpes'),
    Q('Le pire endroit pour un premier rendez-vous :', 'Un enterrement', 'Chez le dentiste', 'Un repas de famille', 'Une salle d\'attente de préfecture'),
    Q('Vous pouvez voyager dans le temps une seule fois :', 'Chez les dinosaures', 'À la cour de Louis XIV', 'En l\'an 3000', 'Hier, pour changer une seule chose'),
    Q('Vous êtes transformé en animal pour une journée :', 'Un chat', 'Un aigle', 'Un dauphin', 'Un paresseux'),
    Q('Le bruit le plus insupportable :', 'Une craie sur un tableau', 'Quelqu\'un qui mâche fort', 'Un moustique la nuit', 'Une alarme de voiture'),
    Q('Votre talent caché, si vous deviez en avoir un :', 'Jongler avec des œufs', 'Imiter des animaux', 'Faire du beatbox', 'Parler à l\'envers'),
    Q('Le meilleur moment de la journée :', 'Le café du matin', 'La sieste', 'L\'apéro', 'Le moment où on se glisse dans son lit'),
    Q('Si vous gagniez au loto, vous achèteriez d\'abord :', 'Une île', 'Un château', 'Une voiture de sport', 'Un stock de chocolat à vie'),
    Q('Le pire voisin possible :', 'Un batteur de heavy metal', 'Un coq très matinal', 'Un fan de karaoké', 'Quelqu\'un qui fait des travaux tous les dimanches'),
    Q('Vous ne pouvez plus en utiliser qu\'un seul :', 'Votre téléphone', 'Votre frigo', 'Votre lit', 'Votre douche chaude'),
    Q('Votre film de vie s\'appellerait :', 'Les Aventures d\'un canapé', 'Mission : sieste impossible', 'Retour vers le frigo', 'Le Seigneur des retards'),
    Q('Votre plus grande peur absurde :', 'Les ballons de baudruche', 'Les poupées anciennes', 'Les pigeons', 'Les ascenseurs en verre'),
    Q('Le meilleur dessert de tous les temps :', 'Le tiramisu', 'La mousse au chocolat', 'La tarte aux pommes', 'Le fondant au chocolat'),
    Q('Quel animal ferait le pire président ?', 'Un chat', 'Un paon', 'Un mouton', 'Un perroquet'),
    Q('Vous êtes coincé dans un ascenseur avec :', 'Un mime', 'Un vendeur d\'aspirateurs', 'Votre ex', 'Quelqu\'un qui mange du poisson'),
    Q('La meilleure saison :', 'Le printemps', 'L\'été', 'L\'automne', 'L\'hiver'),
    Q('Votre super-héros préféré parmi ceux-ci :', 'Captain Sieste', 'Wonder Mamie', 'L\'Homme-Raclette', 'Super-Ponctuel'),
    Q('La meilleure façon de passer un dimanche pluvieux :', 'Marathon de séries', 'Jeux de société', 'Cuisiner toute la journée', 'Dormir jusqu\'à 15 h'),
    Q('Le pire objet à oublier en vacances :', 'Son maillot de bain', 'Son chargeur', 'Sa brosse à dents', 'Ses lunettes'),
    Q('Si vous deviez porter le même costume toute votre vie :', 'Un pyjama', 'Un costume de pirate', 'Une combinaison de ski', 'Une tenue de chevalier'),
    Q('Le meilleur accompagnement :', 'Les frites', 'La purée', 'Le riz', 'Les haricots verts'),
    Q('Votre animal totem :', 'Le hibou', 'Le lion', 'Le koala', 'La loutre'),
  ],
});
