const mk = require('./_textquiz');
// d : difficulté (1 facile, 2 moyen, 3 difficile).
const Q = (d, p, e, h, a, ...alias) => ({ d, p, clues: [e, h], a, alias });
const F = 'Quel film ?', X = 'Quelle expression ?', C = 'Quel conte ?', P = 'Quel personnage ?';
module.exports = mk({
  id: 'emojis', category: 'Cinéma & séries', name: 'Devine en emojis', rounds: 5, clueSeconds: 20, categories: ['Cinéma & séries', 'Expressions', 'Personnages'],
  desc: 'Films, dessins animés, contes et expressions racontés en emojis.',
  questions: [
    // ★ Facile
    Q(1, F, '🦁👑', 'Un dessin animé Disney de 1994', 'Le Roi Lion'),
    Q(1, F, '🧊👸❄️', 'Une chanson qu\'on a tous entendue 1000 fois', 'La Reine des neiges', 'Frozen'),
    Q(1, F, '🚢🧊💔', 'Sorti en 1997', 'Titanic'),
    Q(1, F, '🐠🔍', 'Un petit poisson-clown se perd', 'Le Monde de Nemo', 'Nemo', 'Finding Nemo'),
    Q(1, P, '🕷️🕸️🏙️', 'Il balance des toiles', 'Spider-Man', 'Spiderman', 'L\'homme araignée'),
    Q(1, 'Quel duo ?', '🐱🐭💥', 'Un dessin animé de poursuite sans fin', 'Tom et Jerry'),
    Q(1, P, '⚡👓🧙‍♂️', 'Un jeune sorcier avec une cicatrice', 'Harry Potter', 'Harry'),
    Q(1, C, '👠🎃🕛', 'Il faut rentrer avant minuit', 'Cendrillon'),
    Q(1, C, '🍎👸7️⃣', 'Sept petits compagnons qui travaillent à la mine', 'Blanche-Neige', 'Blanche Neige', 'Blanche-Neige et les sept nains'),
    Q(1, C, '👧🔴🐺', 'Elle apporte une galette à sa grand-mère', 'Le Petit Chaperon rouge', 'Petit Chaperon rouge', 'Chaperon rouge'),
    Q(1, C, '3️⃣🐷🐺🏠', 'Maisons en paille, en bois et en briques', 'Les Trois Petits Cochons', 'Trois petits cochons', '3 petits cochons'),
    Q(1, F, '🟢👹🫏', 'Un ogre et un âne bavard', 'Shrek'),
    Q(1, F, '⭐⚔️🌌', 'Que la Force soit avec toi', 'Star Wars', 'La Guerre des étoiles'),
    Q(1, F, '🦖🏝️🚙', 'Un parc d\'attractions qui tourne mal', 'Jurassic Park'),
    Q(1, F, '🐼🥋', 'Un ours très gourmand devient Guerrier Dragon', 'Kung Fu Panda'),
    // ★★ Moyen
    Q(2, F, '🦈🏖️', 'Un classique de 1975 qui fait peur de se baigner', 'Les Dents de la mer', 'Jaws'),
    Q(2, F, '🐀👨‍🍳', 'Ça se passe dans une cuisine à Paris', 'Ratatouille'),
    Q(2, F, '🍫🏭🎫', 'Un ticket doré à gagner', 'Charlie et la chocolaterie'),
    Q(2, F, '🤖🌱❤️', 'Un petit robot nettoyeur', 'WALL-E', 'Wall E', 'Wally'),
    Q(2, F, '🏴‍☠️🦜🌊', 'Johnny Depp en capitaine', 'Pirates des Caraïbes', 'Pirates des Caraibes'),
    Q(2, F, '🤠🚀🧸', 'Des jouets qui prennent vie', 'Toy Story'),
    Q(2, F, '💍🌋🧙', 'Un hobbit doit détruire un bijou', 'Le Seigneur des anneaux', 'Seigneur des anneaux'),
    Q(2, F, '🚗⚡⏰', 'Une DeLorean voyage dans le temps', 'Retour vers le futur', 'Back to the Future'),
    Q(2, F, '🎈🏠👴', 'Une maison s\'envole avec des ballons', 'Là-haut', 'La haut', 'Up'),
    Q(2, F, '📖🌴🐻🐍', 'Mowgli, Baloo et Kaa', 'Le Livre de la jungle', 'Livre de la jungle'),
    Q(2, F, '👽🚲🌕', '« Téléphone… maison… »', 'E.T.', 'ET', 'E.T. l\'extra-terrestre'),
    Q(2, F, '💊🔴🔵🕶️', 'Pilule rouge ou pilule bleue ?', 'Matrix', 'The Matrix'),
    Q(2, F, '👻📞🚫', 'Who you gonna call ?', 'SOS Fantômes', 'SOS Fantomes', 'Ghostbusters'),
    Q(2, P, '🦇🦸‍♂️🌃', 'Le justicier de Gotham City', 'Batman'),
    Q(2, 'Quelle œuvre ?', '🤴🌹🪐', '« S\'il vous plaît… dessine-moi un mouton ! »', 'Le Petit Prince', 'Petit Prince'),
    Q(2, X, '🐰📍⏰', 'Quand on ne vient pas à un rendez-vous', 'Poser un lapin'),
    Q(2, X, '👀💰', 'Quand c\'est vraiment très cher', 'Coûter les yeux de la tête', 'Couter les yeux de la tete'),
    Q(2, X, '🌧️🪢', 'Quand il pleut très fort', 'Il pleut des cordes', 'Pleuvoir des cordes'),
    Q(2, X, '🙂☁️☁️', 'Être distrait, rêveur', 'Avoir la tête dans les nuages', 'La tête dans les nuages'),
    Q(2, X, '🗣️🥗', 'Dire des mensonges', 'Raconter des salades'),
    Q(2, X, '🍎🍎⬇️', 'S\'évanouir', 'Tomber dans les pommes'),
    // ★★★ Difficile
    Q(3, X, '🦶🍽️', 'Aborder maladroitement un sujet délicat', 'Mettre les pieds dans le plat'),
    Q(3, X, '🐱🗣️', 'Quand la voix est enrouée', 'Avoir un chat dans la gorge', 'Un chat dans la gorge'),
    Q(3, X, '🪳😞', 'Avoir le moral à zéro', 'Avoir le cafard'),
    Q(3, X, '✋🌱💚', 'Être doué pour le jardinage', 'Avoir la main verte'),
    Q(3, X, '✋🦱😴', 'Être très paresseux', 'Avoir un poil dans la main', 'Un poil dans la main'),
    Q(3, X, '🐂🐂⬅️🚜', 'Faire les choses dans le mauvais ordre', 'Mettre la charrue avant les bœufs', 'Mettre la charrue avant les boeufs'),
    Q(3, F, '🛡️⏳🏙️', 'Jacquouille la Fripouille débarque au XXe siècle', 'Les Visiteurs'),
    Q(3, F, '👩🏻📷🍮', 'Une jeune Montmartroise et une crème brûlée', 'Le Fabuleux Destin d\'Amélie Poulain', 'Amélie Poulain', 'Amélie'),
    Q(3, F, '💤🌀🏙️', 'Des rêves dans des rêves', 'Inception'),
    Q(3, F, '🌽🚀🕳️', 'Des champs de maïs et un trou noir', 'Interstellar'),
    Q(3, F, '🤫🐑🐑', 'Hannibal Lecter', 'Le Silence des agneaux', 'Silence des agneaux'),
    Q(3, F, '🏠⬆️🍟', 'Un postier muté dans le Nord', 'Bienvenue chez les Ch\'tis', 'Bienvenue chez les Chtis'),
    Q(3, F, '🤠🐍📦', 'Un archéologue au chapeau et au fouet', 'Les Aventuriers de l\'arche perdue', 'Indiana Jones'),
    Q(3, F, '🌪️👠🛣️💛', 'Suivez la route de briques jaunes', 'Le Magicien d\'Oz', 'Magicien d\'Oz'),
    Q(3, F, '🌹🍊🤵', 'Une offre qu\'on ne peut pas refuser', 'Le Parrain', 'The Godfather'),
    Q(3, F, '🇬🇷🎤💃', 'Une comédie musicale sur les tubes d\'ABBA', 'Mamma Mia', 'Mamma Mia!'),
  ],
});
