const mk = require('./_textquiz');
// d : difficulté (1 facile, 2 moyen, 3 difficile).
const Q = (d, q, a, ...alias) => ({ d, p: 'Répondez vite !', clues: [q], a, alias });
module.exports = mk({
  id: 'express', category: 'Culture générale', name: 'Réponse express', rounds: 8, clueSeconds: 8, categories: ['Culture générale', 'Géographie', 'Sciences', 'Sport', 'Vie quotidienne'],
  desc: 'Des questions de plus en plus corsées, mais seulement 8 secondes pour répondre.',
  questions: [
    // ★ Facile
    Q(1, 'Capitale de l\'Italie ?', 'Rome'), Q(1, 'Couleur du cheval blanc d\'Henri IV ?', 'blanc'),
    Q(1, 'Combien de jours dans une semaine ?', '7', 'sept'), Q(1, 'Capitale de l\'Espagne ?', 'Madrid'),
    Q(1, 'Combien de côtés a un hexagone ?', '6', 'six'), Q(1, 'Quel fleuve traverse Paris ?', 'la Seine', 'Seine'),
    Q(1, 'Quelle planète est surnommée la planète rouge ?', 'Mars'),
    Q(1, 'Combien de joueurs sur le terrain dans une équipe de foot ?', '11', 'onze'),
    Q(1, 'Quel animal miaule ?', 'chat', 'un chat'), Q(1, 'Quel mois suit janvier ?', 'février', 'fevrier'),
    Q(1, 'Combien de minutes dans une heure ?', '60', 'soixante'), Q(1, 'Capitale de l\'Allemagne ?', 'Berlin'),
    Q(1, 'Bleu + jaune = quelle couleur ?', 'vert'), Q(1, 'Quel animal est surnommé le roi de la jungle ?', 'le lion', 'lion'),
    Q(1, 'Combien de lettres dans l\'alphabet ?', '26', 'vingt six'), Q(1, '10 × 10 = ?', '100', 'cent'),
    Q(1, 'Combien de pattes a une araignée ?', '8', 'huit'), Q(1, 'Combien de mois dans une année ?', '12', 'douze'),
    Q(1, 'Capitale du Royaume-Uni ?', 'Londres', 'London'), Q(1, 'Quel insecte fabrique le miel ?', 'abeille', 'l abeille'),
    Q(1, 'Quel pays a la forme d\'une botte ?', 'Italie', 'l Italie'), Q(1, 'Combien de faces a un cube ?', '6', 'six'),
    Q(1, 'Combien d\'heures dans une journée ?', '24', 'vingt quatre'), Q(1, 'Capitale de la Belgique ?', 'Bruxelles'),
    Q(1, 'Dans quel pays mange-t-on traditionnellement des sushis ?', 'Japon', 'le Japon'),
    Q(1, 'Quel instrument a 88 touches noires et blanches ?', 'piano', 'le piano'),
    Q(1, 'Rouge + blanc = quelle couleur ?', 'rose'),
    // ★★ Moyen
    Q(2, 'Le plus grand océan du monde ?', 'Pacifique', 'océan Pacifique'), Q(2, 'Quelle langue parle-t-on au Brésil ?', 'portugais'),
    Q(2, '2 + 2 × 2 = ?', '6', 'six'), Q(2, 'Le plus grand mammifère marin ?', 'baleine bleue', 'baleine'),
    Q(2, '7 × 8 = ?', '56', 'cinquante six'), Q(2, 'Quel est l\'animal terrestre le plus rapide ?', 'le guépard', 'guepard'),
    Q(2, 'Formule chimique de l\'eau ?', 'H2O'), Q(2, 'Capitale du Canada ?', 'Ottawa'),
    Q(2, 'Symbole chimique de l\'or ?', 'Au'), Q(2, 'Monnaie du Japon ?', 'yen', 'le yen'),
    Q(2, 'Plus haute montagne du monde ?', 'Everest', 'mont Everest'), Q(2, 'Qui a écrit Les Misérables ?', 'Victor Hugo', 'Hugo'),
    Q(2, 'Combien de cordes sur une guitare classique ?', '6', 'six'), Q(2, 'Le plus long fleuve de France ?', 'la Loire', 'Loire'),
    Q(2, 'Combien de zéros dans un million ?', '6', 'six'), Q(2, '9 × 7 = ?', '63', 'soixante trois'),
    Q(2, 'Capitale du Portugal ?', 'Lisbonne', 'Lisboa'), Q(2, 'Capitale de la Suisse ?', 'Berne', 'Bern'),
    Q(2, 'Qui a peint La Joconde ?', 'Léonard de Vinci', 'de Vinci', 'Vinci', 'Leonard de Vinci', 'da Vinci'),
    Q(2, 'Racine carrée de 81 ?', '9', 'neuf'), Q(2, 'Combien de côtés a un octogone ?', '8', 'huit'),
    Q(2, 'Combien de joueurs par équipe sur un terrain de basket ?', '5', 'cinq'),
    Q(2, 'Combien de joueurs par équipe sur un terrain de volley ?', '6', 'six'),
    Q(2, 'Monnaie du Royaume-Uni ?', 'livre sterling', 'livre', 'pound'), Q(2, 'Langue officielle du Mexique ?', 'espagnol'),
    Q(2, 'En quelle année s\'est terminée la Seconde Guerre mondiale ?', '1945'), Q(2, '17 × 3 = ?', '51', 'cinquante et un'),
    // ★★★ Difficile
    Q(3, 'Capitale de l\'Australie ?', 'Canberra'), Q(3, 'Symbole chimique du fer ?', 'Fe'),
    Q(3, 'Symbole chimique du sodium ?', 'Na'), Q(3, '13 × 13 = ?', '169'),
    Q(3, 'Capitale de la Turquie ?', 'Ankara'), Q(3, 'Plus petit pays du monde ?', 'Vatican', 'le Vatican'),
    Q(3, 'Planète la plus proche du Soleil ?', 'Mercure'), Q(3, 'Capitale du Brésil ?', 'Brasilia'),
    Q(3, 'Combien de cœurs a une pieuvre ?', '3', 'trois'), Q(3, 'Os le plus long du corps humain ?', 'fémur', 'femur'),
    Q(3, 'Qui a écrit Germinal ?', 'Émile Zola', 'Zola', 'Emile Zola'), Q(3, 'Capitale de la Nouvelle-Zélande ?', 'Wellington'),
    Q(3, 'Racine carrée de 144 ?', '12', 'douze'), Q(3, 'Plus long fleuve d\'Europe ?', 'Volga', 'la Volga'),
    Q(3, 'Gaz le plus abondant dans l\'air ?', 'azote', 'diazote', 'l azote'), Q(3, 'Combien de minutes dans une journée ?', '1440'),
    Q(3, 'Capitale du Maroc ?', 'Rabat'), Q(3, 'Capitale de l\'Écosse ?', 'Édimbourg', 'Edimbourg', 'Edinburgh'),
    Q(3, 'Quel pays est surnommé « le pays des mille lacs » ?', 'Finlande', 'la Finlande'),
    Q(3, 'Combien de joueurs par équipe sur un terrain de rugby à XV ?', '15', 'quinze'),
    Q(3, 'Combien de secondes dans une journée ?', '86400'), Q(3, 'Symbole chimique de l\'argent ?', 'Ag'),
  ],
});
