const mk = require('./_textquiz');
// d : difficulté (1 facile, 2 moyen, 3 difficile).
const Q = (d, r, y, a, ...alias) => ({ d, p: 'Quel film se cache derrière ce résumé ?', clues: [r, `Indice : sorti en ${y}`], a, alias });
module.exports = mk({
  id: 'filmresume', category: 'Cinéma & séries', name: 'Film résumé très mal', rounds: 5, clueSeconds: 25, categories: ['Cinéma & séries', 'Comédie', 'Aventure'],
  desc: 'Retrouvez le film à partir d\'un résumé volontairement catastrophique.',
  questions: [
    // ★ Facile
    Q(1, 'Un homme dessine une femme puis un gros glaçon gagne contre un bateau.', 1997, 'Titanic'),
    Q(1, 'Un chaton refuse de rentrer chez lui, puis part en vacances avec un phacochère.', 1994, 'Le Roi Lion'),
    Q(1, 'Un orphelin découvre qu\'il est sorcier et que son école a un énorme problème de sécurité.', 2001, 'Harry Potter', 'Harry Potter à l\'école des sorciers'),
    Q(1, 'Un monstre vert part en voyage avec un âne qui parle beaucoup trop.', 2001, 'Shrek'),
    Q(1, 'Des jouets font une crise de jalousie à cause d\'un cow-boy et d\'un astronaute.', 1995, 'Toy Story'),
    Q(1, 'Des scientifiques ouvrent un parc d\'attractions sans penser à l\'assurance.', 1993, 'Jurassic Park'),
    Q(1, 'Une princesse congèle tout son royaume parce qu\'elle ne sait pas gérer ses émotions.', 2013, 'La Reine des neiges', 'Frozen'),
    Q(1, 'Un père surprotecteur traverse l\'océan avec une amie qui oublie tout au bout de dix secondes.', 2003, 'Le Monde de Nemo', 'Nemo'),
    Q(1, 'Une jeune femme perd une chaussure, et un prince fait essayer cette chaussure à tout le royaume.', 1950, 'Cendrillon'),
    Q(1, 'Un jeune fermier quitte sa planète désertique et apprend à se battre avec une lampe de poche.', 1977, 'Star Wars', 'La Guerre des étoiles'),
    Q(1, 'Un lycéen se fait mordre par un insecte et n\'achète plus jamais de corde.', 2002, 'Spider-Man', 'Spiderman'),
    Q(1, 'Un rongeur dirige un commis de cuisine en lui tirant les cheveux.', 2007, 'Ratatouille'),
    Q(1, 'Un voleur trouve une vieille lampe et se fait un ami bleu extrêmement bavard.', 1992, 'Aladdin'),
    Q(1, 'Un méchant chauve veut voler la Lune, mais trois orphelines le rendent tout gentil.', 2010, 'Moi, moche et méchant', 'Moi moche et mechant', 'Despicable Me'),
    // ★★ Moyen
    Q(2, 'Un petit homme marche très longtemps pour jeter une bague dans un volcan.', 2001, 'Le Seigneur des anneaux', 'Seigneur des anneaux', 'La communauté de l\'anneau'),
    Q(2, 'Un maire refuse de fermer la plage malgré un gros poisson.', 1975, 'Les Dents de la mer', 'Jaws'),
    Q(2, 'Deux hommes que tout oppose font des tours de voiture et mangent des pâtisseries.', 2011, 'Intouchables'),
    Q(2, 'Un informaticien apprend que sa vie est fausse et décide de porter un long manteau.', 1999, 'Matrix', 'The Matrix'),
    Q(2, 'Un chevalier et son écuyer arrivent à notre époque et se plaignent de tout.', 1993, 'Les Visiteurs'),
    Q(2, 'Un homme court beaucoup puis raconte sa vie à des inconnus sur un banc.', 1994, 'Forrest Gump'),
    Q(2, 'Un adolescent doit absolument empêcher sa propre mère de tomber amoureuse de lui.', 1985, 'Retour vers le futur', 'Back to the Future'),
    Q(2, 'Un vieux monsieur refuse de déménager, alors il emmène sa maison avec lui.', 2009, 'Là-haut', 'La haut', 'Up'),
    Q(2, 'Un enfant cache un touriste perdu dans son placard et l\'emmène faire du vélo.', 1982, 'E.T.', 'ET', 'E.T. l\'extra-terrestre'),
    Q(2, 'De très grands êtres bleus défendent leur arbre contre une entreprise minière.', 2009, 'Avatar'),
    Q(2, 'Un jeu de société très mal conçu transforme une maison en zoo.', 1995, 'Jumanji'),
    Q(2, 'Un architecte a trois mois pour construire un palais, heureusement il a des amis dopés.', 2002, 'Astérix et Obélix : Mission Cléopâtre', 'Mission Cléopâtre', 'Astérix', 'Asterix'),
    Q(2, 'Un postier muté dans le Nord découvre qu\'il ne pleut pas tant que ça.', 2008, 'Bienvenue chez les Ch\'tis', 'Bienvenue chez les Chtis'),
    Q(2, 'Un livreur de pizzas marseillais aide un policier qui ne sait pas conduire.', 1998, 'Taxi'),
    Q(2, 'Un professeur d\'université a très peur des serpents, mais pas du tout des nazis.', 1981, 'Les Aventuriers de l\'arche perdue', 'Indiana Jones'),
    Q(2, 'Un pirate toujours ivre cherche désespérément son bateau.', 2003, 'Pirates des Caraïbes', 'Pirates des Caraibes'),
    Q(2, 'Une jeune femme tombe amoureuse de son ravisseur poilu et discute avec la vaisselle.', 1991, 'La Belle et la Bête', 'La Belle et la Bete'),
    Q(2, 'Une future mariée invite ses trois pères potentiels pour être sûre de ne pas se tromper.', 2008, 'Mamma Mia', 'Mamma Mia!'),
    Q(2, 'Un fantôme supplie une fausse voyante de l\'aider, il y a de la poterie.', 1990, 'Ghost'),
    // ★★★ Difficile
    Q(3, 'Un chef de famille règle ses problèmes de voisinage de façon assez directe.', 1972, 'Le Parrain', 'The Godfather'),
    Q(3, 'Une serveuse montmartroise passe son temps à déplacer des nains de jardin.', 2001, 'Le Fabuleux Destin d\'Amélie Poulain', 'Amélie Poulain', 'Amélie'),
    Q(3, 'Des cambrioleurs font la sieste en groupe pour voler une idée.', 2010, 'Inception'),
    Q(3, 'Un père part en voyage d\'affaires et revient plus jeune que sa fille.', 2014, 'Interstellar'),
    Q(3, 'Une stagiaire demande conseil à un psychiatre au régime alimentaire très particulier.', 1991, 'Le Silence des agneaux', 'Silence des agneaux'),
    Q(3, 'Une bande d\'amis se perd en montagne et goûte un fromage local très spécial.', 1979, 'Les Bronzés font du ski', 'Les Bronzés', 'Les Bronzes font du ski'),
    Q(3, 'Un éditeur invite un passionné de maquettes en allumettes et se bloque le dos.', 1998, 'Le Dîner de cons', 'Le Diner de cons'),
    Q(3, 'Un chef d\'orchestre et un peintre en bâtiment aident des aviateurs anglais à traverser la France.', 1966, 'La Grande Vadrouille'),
    Q(3, 'Un psychologue aide un enfant qui voit des gens, mais rate un petit détail le concernant.', 1999, 'Le Sixième Sens', 'Sixième sens', 'Sixieme sens', 'The Sixth Sense'),
    Q(3, 'Une femme choisit vraiment le mauvais motel pour prendre une douche.', 1960, 'Psychose', 'Psycho'),
    Q(3, 'Un employé de bureau insomniaque fonde un club dont il ne faut surtout pas parler.', 1999, 'Fight Club'),
    Q(3, 'Un banquier passe vingt ans à décorer sa cellule avec des posters.', 1994, 'Les Évadés', 'Les Evades', 'The Shawshank Redemption'),
    Q(3, 'Un général romain se reconvertit dans le spectacle vivant.', 2000, 'Gladiator'),
    Q(3, 'Un chauffeur de taxi sauve l\'univers avec une jeune femme tombée sur son toit.', 1997, 'Le Cinquième Élément', 'Le Cinquième Element', 'Le 5e Element', 'The Fifth Element'),
    Q(3, 'Un espion français très sûr de lui ne comprend absolument rien à l\'Égypte.', 2006, 'OSS 117 : Le Caire, nid d\'espions', 'OSS 117', 'OSS 117 Le Caire nid d espions'),
    Q(3, 'Un surveillant transforme des cancres d\'internat en chorale.', 2004, 'Les Choristes'),
    Q(3, 'Un attaché de presse doit promouvoir un film d\'horreur à Cannes pendant qu\'un tueur s\'en prend aux projectionnistes.', 1994, 'La Cité de la peur', 'La Cite de la peur'),
  ],
});
