module.exports = require('./_textvote')({
  id: 'finislaphrase', category: 'Humour', name: 'Finis la phrase', title: 'Finissez la phrase', categories: ['Humour', 'Vie quotidienne', 'Famille'],
  desc: 'Une phrase commencée, à vous de la finir de la façon la plus drôle.',
  prompts: [
    'Mon voisin est tellement bizarre que…',
    'La vraie raison pour laquelle les dinosaures ont disparu, c\'est que…',
    'Si j\'étais président pour une journée, je commencerais par…',
    'Juste avant de faire une bêtise, je dis toujours…',
    'Mon plus grand talent inutile, c\'est…',
    'Le secret d\'une bonne baguette, c\'est…',
    'Si mon chien pouvait parler, il dirait…',
    'Le pire moment pour avoir un fou rire, c\'est quand…',
    'Dans mon prochain film, je jouerai…',
    'Ce que personne n\'ose avouer en réunion, c\'est que…',
    'Ma grand-mère m\'a toujours dit que le secret du bonheur, c\'est…',
    'Ce matin, j\'ai failli être en retard parce que…',
    'Le jour où j\'ai rencontré le président, j\'ai simplement dit…',
    'Si j\'étais maire, la première chose que j\'interdirais, ce serait…',
    'Dans ma prochaine vie, je veux être…',
    'Le plus grand mensonge de ma vie, c\'est quand j\'ai dit que…',
    'Le médecin m\'a dit d\'arrêter immédiatement de…',
    'Ce qui me réveille la nuit, c\'est…',
    'Je ne comprendrai jamais pourquoi les gens…',
    'Mon horoscope du jour disait que…',
    'Si je gagnais au loto, la première chose que j\'achèterais, c\'est…',
    'La meilleure façon de rater un premier rendez-vous, c\'est de…',
    'Ma mère a failli s\'évanouir le jour où…',
    'Mon talent caché, que je n\'ai encore jamais montré à personne, c\'est…',
    'Si les chats dirigeaient le monde, ils commenceraient par…',
    'Le jour où j\'ai été coincé dans un ascenseur, j\'ai…',
    'En vacances, je ne pars jamais sans…',
    'Je savais que la soirée allait mal tourner quand…',
    'Mon prof de maths m\'a appris une chose essentielle :…',
    'Au restaurant, je suis le genre de personne qui…',
    'Si j\'avais une machine à remonter le temps, j\'irais…',
    'Mon voisin du dessus fait un bruit bizarre chaque nuit : il…',
    'La première règle du club secret de mon immeuble, c\'est…',
    'Je suis devenu célèbre sur Internet le jour où…',
    'Le Père Noël a arrêté de venir chez moi depuis que…',
    'Pour séduire quelqu\'un, ma technique infaillible, c\'est…',
    'Le pire job d\'été que j\'aie jamais fait, c\'était…',
    'Si j\'étais un super-héros, mon point faible serait…',
    'Le plus beau compliment qu\'on m\'ait fait, c\'est…',
    'Ma plante verte est morte parce que…',
    'Mon meilleur ami me connaît tellement bien qu\'il sait que…',
    'Quand je chante sous la douche, les voisins…',
    'Le jour de mes 100 ans, je compte…',
    'Le Wi-Fi a coupé pendant une heure et j\'ai découvert que…',
    'La dernière fois que j\'ai cuisiné, les pompiers…',
  ],
});
