module.exports = require('./_textvote')({
  id: 'funny', category: 'Humour', name: 'Réponse la plus drôle', title: 'Écrivez votre réponse', categories: ['Humour', 'Vie quotidienne', 'Cinéma'],
  desc: 'Une question absurde, vous écrivez, on vote pour la meilleure.',
  prompts: [
    'La pire excuse pour arriver en retard à un mariage :',
    'Le nom du pire super-héros de l\'histoire :',
    'Ce qu\'il ne faut jamais dire à son boulanger :',
    'Le titre du film le moins attendu de l\'année :',
    'Une règle absurde qu\'un pays aurait vraiment inventée :',
    'Ce que le chat pense vraiment de nous :',
    'Le pire cadeau à offrir à sa belle-mère :',
    'La phrase qu\'on entend juste avant une catastrophe :',
    'Le slogan d\'un dentiste peu rassurant :',
    'Un métier qui n\'existe pas encore mais qui devrait :',
    'Le pire nom pour un restaurant :',
    'Ce qu\'un extraterrestre écrirait sur Tripadvisor après sa visite sur Terre :',
    'La pire chose à crier dans une bibliothèque :',
    'Le nouveau parfum de chips que personne n\'a demandé :',
    'Ce que les pigeons se racontent vraiment :',
    'La pire première phrase pour un discours de témoin de mariage :',
    'Une application inutile qui ferait un carton :',
    'Ce qu\'on trouve vraiment dans le sac de Mary Poppins :',
    'La pire idée d\'attraction pour un parc de loisirs :',
    'Le message d\'absence le plus honnête au bureau :',
    'Le nom d\'un groupe de rock composé uniquement de grands-mères :',
    'Ce que le GPS dit quand il en a vraiment marre :',
    'La pire chose à dire lors d\'un entretien d\'embauche :',
    'Une nouvelle épreuve olympique franchement ridicule :',
    'Ce que les plantes pensent quand on oublie de les arroser :',
    'Le pire thème pour une soirée déguisée :',
    'Une fausse excuse pour ne pas aller à la salle de sport :',
    'Le titre de l\'autobiographie de votre frigo :',
    'Ce qu\'il ne faut surtout pas écrire sur une carte d\'anniversaire :',
    'Le pire conseil de vie donné par un horoscope :',
    'Le slogan publicitaire d\'une eau minérale très prétentieuse :',
    'La vraie raison pour laquelle les chaussettes disparaissent dans la machine :',
    'Une nouvelle loi que votre chat voterait immédiatement :',
    'La pire chose à entendre de la part d\'un pilote d\'avion :',
    'Le nom d\'une boisson énergisante pour les paresseux :',
    'Le pire mot de passe de l\'histoire :',
    'Le dernier SMS qu\'on recevrait avant la fin du monde :',
    'Ce qu\'on ne veut jamais lire sur l\'emballage d\'un sandwich :',
    'Une émission de télé-réalité qui ne devrait jamais exister :',
    'Le pire surnom à donner à son patron :',
    'Ce que le Père Noël fait vraiment le reste de l\'année :',
    'La pire musique pour un enterrement :',
    'Une mauvaise idée de tatouage :',
    'Ce que votre aspirateur robot pense de votre appartement :',
    'Le pire nom pour un bateau :',
  ],
});
