const mk = require('./_choice');
// d : difficulté (1 facile, 2 moyen, 3 difficile). Le premier élément est l'intrus.
const Q = (d, items, r) => ({ d, p: 'Quel est l\'intrus ?', options: items.map((t, i) => (i === 0 ? { t, ok: true, r } : { t })) });
module.exports = mk({
  id: 'intrus', category: 'Culture générale', name: 'L\'intrus', rounds: 6, points: 500, mode: 'correct', title: 'Trouvez l\'intrus', seconds: 20, revealSeconds: 8, categories: ['Culture générale', 'Géographie', 'Sciences', 'Sport'],
  desc: 'Quatre propositions, une seule ne va pas avec les autres.',
  revealTitle: (q) => `L'intrus : ${q.options.find(o => o.ok).t}`,
  questions: [
    // ★ Facile
    Q(1, ['Carotte', 'Pomme', 'Poire', 'Banane'], 'C\'est un légume, les autres sont des fruits.'),
    Q(1, ['Madrid', 'Paris', 'Lyon', 'Marseille'], 'Les autres sont des villes françaises.'),
    Q(1, ['Triangle', 'Rouge', 'Bleu', 'Vert'], 'Ce n\'est pas une couleur.'),
    Q(1, ['Loup', 'Lion', 'Tigre', 'Panthère'], 'Ce n\'est pas un félin.'),
    Q(1, ['Natation', 'Football', 'Basket', 'Handball'], 'Les autres se jouent avec un ballon.'),
    Q(1, ['Voiture', 'Chien', 'Chat', 'Lapin'], 'Ce n\'est pas un animal.'),
    Q(1, ['Juillet', 'Lundi', 'Mardi', 'Vendredi'], 'C\'est un mois, les autres sont des jours.'),
    Q(1, ['Trompette', 'Guitare', 'Violon', 'Harpe'], 'C\'est un instrument à vent, les autres ont des cordes.'),
    Q(1, ['Décembre', 'Hiver', 'Été', 'Printemps'], 'C\'est un mois, les autres sont des saisons.'),
    Q(1, ['Golf', 'Tennis', 'Badminton', 'Ping-pong'], 'Les autres se jouent avec une raquette.'),
    Q(1, ['Sahara', 'Alpes', 'Pyrénées', 'Vosges'], 'C\'est un désert, les autres sont des montagnes.'),
    Q(1, ['Van Gogh', 'Mozart', 'Chopin', 'Vivaldi'], 'C\'est un peintre, les autres sont des compositeurs.'),
    Q(1, ['Federer', 'Cristiano Ronaldo', 'Messi', 'Zidane'], 'C\'est un joueur de tennis, les autres sont des footballeurs.'),
    Q(1, ['Dumbo', 'Simba', 'Nala', 'Mufasa'], 'Les autres sont des personnages du Roi Lion.'),
    Q(1, ['Mozzarella', 'Roquefort', 'Camembert', 'Brie'], 'C\'est un fromage italien, les autres sont français.'),
    Q(1, ['Colisée', 'Pyramide', 'Sphinx', 'Pharaon'], 'Il est à Rome, les autres évoquent l\'Égypte antique.'),
    Q(1, ['Euro', 'Mètre', 'Litre', 'Kilogramme'], 'C\'est une monnaie, les autres sont des unités de mesure.'),
    // ★★ Moyen
    Q(2, ['Tamise', 'Seine', 'Loire', 'Rhône'], 'Les autres sont des fleuves français.'),
    Q(2, ['Lune', 'Mars', 'Vénus', 'Saturne'], 'C\'est un satellite, les autres sont des planètes.'),
    Q(2, ['Molière', 'Mozart', 'Beethoven', 'Bach'], 'C\'est un écrivain, les autres sont des compositeurs.'),
    Q(2, ['Requin', 'Dauphin', 'Baleine', 'Orque'], 'C\'est un poisson, les autres sont des mammifères marins.'),
    Q(2, ['Chauve-souris', 'Moineau', 'Aigle', 'Pigeon'], 'C\'est un mammifère, les autres sont des oiseaux.'),
    Q(2, ['Soleil', 'Mercure', 'Vénus', 'Mars'], 'C\'est une étoile, les autres sont des planètes.'),
    Q(2, ['Picasso', 'Monet', 'Renoir', 'Degas'], 'Peintre espagnol cubiste ; les autres sont des impressionnistes français.'),
    Q(2, ['Mexique', 'Brésil', 'Argentine', 'Chili'], 'Il est en Amérique du Nord, les autres en Amérique du Sud.'),
    Q(2, ['Genève', 'Athènes', 'Rome', 'Lisbonne'], 'Ce n\'est pas une capitale.'),
    Q(2, ['Grenouille', 'Tortue', 'Serpent', 'Lézard'], 'C\'est un amphibien, les autres sont des reptiles.'),
    Q(2, ['Araignée', 'Fourmi', 'Abeille', 'Papillon'], 'Elle a 8 pattes : ce n\'est pas un insecte.'),
    Q(2, ['Tomate', 'Pomme de terre', 'Carotte', 'Radis'], 'Elle ne pousse pas sous la terre.'),
    Q(2, ['Shakespeare', 'Hugo', 'Zola', 'Balzac'], 'C\'est un auteur anglais, les autres sont français.'),
    Q(2, ['Carré', 'Cube', 'Sphère', 'Pyramide'], 'C\'est une figure plane, les autres sont des volumes.'),
    Q(2, ['15', '7', '11', '13'], 'Ce n\'est pas un nombre premier (15 = 3 × 5).'),
    Q(2, ['Allemand', 'Italien', 'Espagnol', 'Portugais'], 'Langue germanique ; les autres sont des langues latines.'),
    Q(2, ['Garfield', 'Mickey', 'Donald', 'Dingo'], 'Ce n\'est pas un personnage Disney.'),
    Q(2, ['Baguette', 'Croissant', 'Pain au chocolat', 'Chausson aux pommes'], 'Ce n\'est pas une viennoiserie.'),
    Q(2, ['Piano', 'Violon', 'Alto', 'Violoncelle'], 'Instrument à clavier ; les autres sont des cordes frottées avec un archet.'),
    Q(2, ['Plomb', 'Hydrogène', 'Hélium', 'Néon'], 'C\'est un métal, les autres sont des gaz.'),
    // ★★★ Difficile
    Q(3, ['Neptune', 'Zeus', 'Apollon', 'Héra'], 'C\'est un dieu romain, les autres sont des dieux grecs.'),
    Q(3, ['Cheval', 'Vache', 'Mouton', 'Chèvre'], 'Ce n\'est pas un ruminant.'),
    Q(3, ['Rennes', 'Rouen', 'Caen', 'Le Havre'], 'Elle est en Bretagne, les autres en Normandie.'),
    Q(3, ['Sydney', 'Canberra', 'Ottawa', 'Brasilia'], 'Ce n\'est pas une capitale (celle de l\'Australie est Canberra).'),
    Q(3, ['42', '16', '25', '36'], 'Ce n\'est pas un carré parfait.'),
    Q(3, ['Pluton', 'Jupiter', 'Uranus', 'Neptune'], 'C\'est une planète naine depuis 2006.'),
    Q(3, ['Dromadaire', 'Lama', 'Alpaga', 'Vigogne'], 'Il ne vit pas à l\'état naturel en Amérique du Sud.'),
    Q(3, ['Waterloo', 'Austerlitz', 'Iéna', 'Wagram'], 'C\'est une défaite de Napoléon, les autres sont des victoires.'),
    Q(3, ['Le Rouge et le Noir', 'Les Misérables', 'Notre-Dame de Paris', 'Les Contemplations'], 'Écrit par Stendhal ; les autres sont de Victor Hugo.'),
    Q(3, ['Aigle', 'Kiwi', 'Autruche', 'Émeu'], 'Il sait voler, les autres non.'),
    Q(3, ['Manchot', 'Ours polaire', 'Morse', 'Renard arctique'], 'Il vit dans l\'hémisphère sud, les autres dans l\'Arctique.'),
    Q(3, ['Brésil', 'Belgique', 'Suisse', 'Canada'], 'Le français n\'y est pas une langue officielle.'),
    Q(3, ['Mercure', 'Fer', 'Cuivre', 'Zinc'], 'C\'est un métal liquide à température ambiante.'),
    Q(3, ['Saturne', 'Mars', 'Mercure', 'Vénus'], 'C\'est une planète gazeuse, les autres sont rocheuses.'),
  ],
});
