const mk = require('./_textquiz');
// d : difficulté (1 facile, 2 moyen, 3 difficile).
const Q = (d, e, a, ...alias) => ({ d, e: e.join('   '), a, alias });
const letters = (w) => [...w].filter(c => /\p{L}/u.test(c)).length;
module.exports = mk({
  id: 'quatreimages', category: 'Culture pop', name: '4 images 1 mot', rounds: 5, clueSeconds: 20, prompt: 'Quel mot relie ces 4 images ?', categories: ['Culture pop', 'Voyage & lieux', 'Gastronomie', 'Sport', 'Vie quotidienne'],
  desc: 'Quatre emojis, un seul mot en commun. Un indice arrive si ça traîne.',
  clues: (q) => [q.e, `Indice : ${letters(q.a)} lettres`],
  questions: [
    // ★ Facile
    Q(1, ['🌞', '🏖️', '🍹', '🕶️'], 'vacances', 'les vacances', 'été', 'ete'),
    Q(1, ['🎂', '🕯️', '🎁', '🎈'], 'anniversaire', 'fête', 'fete'),
    Q(1, ['🔥', '🏕️', '🌲', '⛺'], 'camping', 'camp'),
    Q(1, ['☔', '🌧️', '🌂', '⛈️'], 'pluie', 'la pluie'),
    Q(1, ['🍕', '🍝', '🍷', '🛵'], 'Italie', 'l\'Italie'),
    Q(1, ['❄️', '⛷️', '🏔️', '🧣'], 'hiver', 'ski', 'neige', 'montagne'),
    Q(1, ['📚', '✏️', '🎒', '🏫'], 'école', 'ecole', 'rentrée', 'la rentrée'),
    Q(1, ['🥖', '🧀', '🍷', '🗼'], 'France', 'la France'),
    Q(1, ['⚽', '🏆', '🥅', '🏟️'], 'football', 'foot'),
    Q(1, ['🌙', '⭐', '🛏️', '😴'], 'nuit', 'dodo', 'sommeil', 'dormir'),
    Q(1, ['🎄', '🎅', '🎁', '⛄'], 'Noël', 'Noel'),
    Q(1, ['🌊', '🐚', '🐟', '⛵'], 'mer', 'la mer', 'océan', 'ocean', 'plage'),
    Q(1, ['🎸', '🎹', '🎤', '🎧'], 'musique', 'la musique', 'concert'),
    Q(1, ['🍳', '🔪', '🥄', '👩‍🍳'], 'cuisine', 'la cuisine', 'cuisiner'),
    Q(1, ['🐄', '🐖', '🐓', '🚜'], 'ferme', 'la ferme', 'campagne'),
    Q(1, ['🎬', '🍿', '🎟️', '🎥'], 'cinéma', 'cinema', 'film'),
    // ★★ Moyen
    Q(2, ['🎃', '👻', '🦇', '🍬'], 'Halloween'),
    Q(2, ['💍', '👰', '🤵', '💒'], 'mariage', 'noces'),
    Q(2, ['🏴‍☠️', '🦜', '💰', '⚓'], 'pirate', 'pirates', 'trésor'),
    Q(2, ['🚀', '🪐', '👨‍🚀', '🌌'], 'espace', 'l\'espace', 'cosmos', 'univers'),
    Q(2, ['🍣', '🗻', '🎎', '🌸'], 'Japon', 'le Japon'),
    Q(2, ['🤡', '🎪', '🦁', '🤹'], 'cirque', 'le cirque'),
    Q(2, ['🏥', '🩺', '💉', '🚑'], 'hôpital', 'hopital', 'médecin', 'santé', 'urgences'),
    Q(2, ['🌷', '🪴', '🐌', '💧'], 'jardin', 'jardinage'),
    Q(2, ['🎩', '🐇', '🪄', '✨'], 'magie', 'magicien'),
    Q(2, ['🧺', '🥪', '🌳', '🍉'], 'pique-nique', 'pique nique', 'piquenique'),
    Q(2, ['🍽️', '👨‍🍳', '🍷', '🧾'], 'restaurant', 'resto'),
    Q(2, ['🐫', '🏜️', '🔺', '📜'], 'Égypte', 'Egypte', 'pyramides', 'désert'),
    Q(2, ['🌮', '🌵', '🪅', '🌶️'], 'Mexique', 'le Mexique'),
    Q(2, ['🍂', '🍁', '🌰', '🍄'], 'automne', 'l\'automne'),
    Q(2, ['🚂', '🎫', '🛤️', '🚉'], 'train', 'gare', 'voyage'),
    Q(2, ['🥖', '🥐', '🍞', '🧁'], 'boulangerie', 'boulanger', 'pain'),
    Q(2, ['🐣', '🥚', '🐰', '🔔'], 'Pâques', 'Paques'),
    // ★★★ Difficile
    Q(3, ['💘', '🌹', '🍫', '💌'], 'Saint-Valentin', 'Saint Valentin', 'amour'),
    Q(3, ['🎣', '🐟', '🪱', '🚤'], 'pêche', 'peche', 'pêcheur', 'pecheur'),
    Q(3, ['🎭', '🎟️', '🪑', '👏'], 'théâtre', 'theatre', 'spectacle'),
    Q(3, ['🔭', '🌙', '⭐', '🪐'], 'astronomie', 'astronome', 'étoiles'),
    Q(3, ['⚔️', '🛡️', '🐴', '🏰'], 'chevalier', 'chevaliers', 'Moyen Âge', 'Moyen Age'),
    Q(3, ['🦷', '🪥', '😬', '💺'], 'dentiste', 'dents'),
    Q(3, ['🧪', '🔬', '🧬', '👩‍🔬'], 'science', 'sciences', 'laboratoire', 'chimie'),
    Q(3, ['🦁', '🦒', '🚙', '📸'], 'safari', 'savane', 'Afrique'),
    Q(3, ['🤿', '🐠', '🐙', '🌊'], 'plongée', 'plongee'),
    Q(3, ['✉️', '📦', '📮', '🚲'], 'poste', 'la poste', 'facteur', 'courrier'),
    Q(3, ['📦', '🚚', '🛋️', '🏠'], 'déménagement', 'demenagement', 'déménager', 'demenager'),
    Q(3, ['🍇', '🧺', '🍷', '🌞'], 'vendanges', 'vendange', 'vigne', 'vin'),
    Q(3, ['🐼', '🥢', '🏮', '🐉'], 'Chine', 'la Chine'),
    Q(3, ['💰', '🏦', '💳', '🔐'], 'banque', 'argent'),
    Q(3, ['🌪️', '⚡', '🌊', '💨'], 'tempête', 'tempete', 'orage', 'ouragan'),
    Q(3, ['🗳️', '🎤', '🏛️', '🤝'], 'politique', 'élection', 'election', 'élections'),
  ],
});
