// Pixel Flou : les personnages en pixel art.
// Chaque sprite est une grille de caractères ; « . » = transparent, les autres lettres renvoient
// à la palette commune ci-dessous (un sprite peut redéfinir des couleurs avec `pal`).
// `like` réutilise la grille d'un autre sprite (ex. Luigi = Mario recoloré).
const PALETTE = {
  K: '#151515', W: '#ffffff', R: '#e52521', r: '#9c1414', B: '#2c5bd6', b: '#1b2f7a', L: '#7ec8f5',
  Y: '#ffd800', O: '#ff8a1e', N: '#8b4a1b', n: '#4a2408', S: '#ffc896', s: '#d9925a', G: '#3cb83c',
  g: '#1e6b1e', l: '#a6e05a', P: '#ff9ec8', p: '#e0507a', U: '#8a4fc8', u: '#4b2a7a', E: '#a8a8a8',
  e: '#5a5a5a', C: '#30c8c0', c: '#1d7f78', T: '#f5deb3', D: '#fff2b0', M: '#d8dce6', A: '#f0b030',
};

const SPRITES = {
  mario: { px: [
    '...RRRRR....',
    '..RRRRRRRRR.',
    '..NNNSSKS...',
    '.NSNSSSKSSS.',
    '.NSNNSSSKSSS',
    '.NNSSSSKKKK.',
    '...SSSSSSS..',
    '..RRBRRR....',
    '.RRRBRRBRRR.',
    'RRRRBBBBRRRR',
    'SSRBYBBYBRSS',
    'SSSBBBBBBSSS',
    'SSBBBBBBBBSS',
    '..BBB..BBB..',
    '.NNN....NNN.',
    'NNNN....NNNN',
  ] },
  luigi: { like: 'mario', pal: { R: '#2fae3a', B: '#24308a' } },
  pikachu: { px: [
    'K................K',
    'KK..............KK',
    '.KY............YK.',
    '.YYY..........YYY.',
    '..YYY........YYY..',
    '...YYYYYYYYYYYY...',
    '..YYYYYYYYYYYYYY..',
    '..YYKKYYYYYYKKYY..',
    '..YYKWYYYYYYKWYY..',
    '..RRYYYYKYYYYYRR..',
    '..RRYYYYYYYYYYRR..',
    '...YYYYKYYKYYYY...',
    '....YYYYKKYYYY..Y.',
    '...YYYYYYYYYYYYYYY',
    '..YYYYYYYYYYYYYYY.',
    '..YYNYYYYYYYYNYY..',
    '..YYYYYYYYYYYYYY..',
    '...YYY......YYY...',
  ] },
  kirby: { px: [
    '.....KKKKKK.....',
    '...KKPPPPPPKK...',
    '..KPPPPPPPPPPK..',
    '.KPPPPPPPPPPPPK.',
    '.KPPPPKPPKPPPPK.',
    'KPPPPPKPPKPPPPPK',
    'KPPPPPBPPBPPPPPK',
    'KPPpPPPPPPPPpPPK',
    'KPPPPPPKKPPPPPPK',
    '.KPPPPPPPPPPPPK.',
    '.KPPPPPPPPPPPPK.',
    '..KPPPPPPPPPPK..',
    '.KRRKKPPPPKKRRK.',
    'KRRRRRKKKKRRRRRK',
    'KRRRRRK..KRRRRRK',
    '.KKKKK....KKKKK.',
  ] },
  sonic: { px: [
    '......BBBBB.....',
    '....BBBBBBBB....',
    '..BBBBBBBBBBB...',
    'BBBBBBBBWWWBWW..',
    '..BBBBBBWWKWKW..',
    '.BBBBBBBWWKWKW..',
    'BBBBBBBBSWWWWS..',
    '...BBBBBSSSSSSK.',
    '..BBBBBBSSSKKSS.',
    '.BBBBBBBBSSSSS..',
    '....BBBBBBB.....',
    '...BBSSSSSBB....',
    '...BBSSSSSBB....',
    '....BBBBBBB.....',
    '...RRWR.RRWR....',
    '..RRRRR.RRRRR...',
  ] },
  link: { px: [
    '.......GG.....M.',
    '......GGGG....M.',
    '.....GGGGGG...M.',
    '....GGGGGGGG..M.',
    '...GGGGGGGGGG.M.',
    '...YYYYYYYYYY.M.',
    '..SYSSSSSSSSYSM.',
    '.SSSSKSSSSKSSSM.',
    '..SSSSSSSSSSSNNN',
    '...SSSSSSSSSS.S.',
    '....SSSSSSSS..S.',
    '..GGGGGGGGGGGGS.',
    '.SGGGGGGGGGGGG..',
    '.SGGNNNYNNNGG...',
    '..GGGGGGGGGGG...',
    '...SS.....SS....',
    '...NN.....NN....',
    '..NNN.....NNN...',
  ] },
  pacman: { px: [
    '....YYYYY....',
    '..YYYYYYYYY..',
    '.YYYYYYYYYYY.',
    '.YYYYYYYYY...',
    'YYYYYYYY.....',
    'YYYYYY.......',
    'YYYY.....W.W.',
    'YYYYYY.......',
    'YYYYYYYY.....',
    '.YYYYYYYYY...',
    '.YYYYYYYYYYY.',
    '..YYYYYYYYY..',
    '....YYYYY....',
  ] },
  yoshi: { px: [
    '.......WWWWWW.....',
    '......WWKWWKWW....',
    '......WWKWWKWW....',
    '.....GGWWGGWWGGG..',
    '..r.GGGGGGGGGGGGGG',
    '.rrrGGGGGGGGGGGGGG',
    '..rGGGGGGGGGKGGGGK',
    '...GGGGWWWWWWWWWW.',
    '...GGGWWWWWWWWWW..',
    '...GGGGWWW........',
    '..RRRRGWWW........',
    '.RRRRRRWWWW.......',
    '.RRRRRRWWW........',
    '..GGGGGWWW........',
    '..GGGGGGGG........',
    '...GGG.GGG........',
    '..OOOO.OOOO.......',
    '..OOOOOOOOOO......',
  ] },
  donkeykong: { pal: { n: '#6b3410', T: '#e8b07a' }, px: [
    '....nnnnnnnn....',
    '...nnnnnnnnnn...',
    '..nnnTTnnTTnnn..',
    '..nnTWKTTWKTnn..',
    '..nnTTTTTTTTnn..',
    '.nnnTTTKKTTTnnn.',
    '.nnnTTTTTTTTnnn.',
    'nnnnnTKKKKTnnnnn',
    'nnnnnnTTTTnnnnnn',
    'nnnnnRRRRRRnnnnn',
    'TTnnnnRRRRnnnnTT',
    'TTnnnnRYYRnnnnTT',
    'TTnnnnnRRnnnnnTT',
    '.nnnnnnnnnnnnnn.',
    '.TTTnnnn.nnnnTTT',
    '..TTTT....TTTT..',
  ] },
  invader: { pal: { K: '#3fe03f' }, px: [
    '..K.....K..',
    '...K...K...',
    '..KKKKKKK..',
    '.KK.KKK.KK.',
    'KKKKKKKKKKK',
    'K.KKKKKKK.K',
    'K.K.....K.K',
    '...KK.KK...',
  ] },
  bowser: { pal: { G: '#8fc93a', T: '#f3d27a', R: '#e8462a' }, px: [
    '.W............W.',
    '.WW..R.RR.R..WW.',
    '..WWRRRRRRRRWW..',
    '..GGRRRRRRRRGG..',
    '.GGGGGGGGGGGGGG.',
    '.GGRRGGGGGGRRGG.',
    'GGGWRGGGGGGRWGGG',
    'GGGGGGGGGGGGGGGG',
    'GGTTTTTTTTTTTTGG',
    'GTTTKKTTTTKKTTTG',
    'GTTTTTTTTTTTTTTG',
    'GTWTTTTTTTTTTWTG',
    '.TTTTTTTTTTTTTT.',
    '..TTTTTTTTTTTT..',
    '.KWKKWKKWKKWKKW.',
    '..KKKKKKKKKKKK..',
  ] },
  peach: { pal: { Y: '#ffd84a', A: '#e8a800' }, px: [
    '.....Y.Y.Y......',
    '.....YCYRY......',
    '...AAYYYYYAA....',
    '..AYYYYYYYYYA...',
    '..YYSSSSSSSYY...',
    '..YSSKSSSKSSY...',
    '..YSSBSSSBSSYY..',
    '..YYSSSSSSSYYY..',
    '..YYYSSpSSYYYY..',
    '..YYYYSSSYYYYYY.',
    '...YYPPPPPYYYY..',
    '....PPPPPPP.YY..',
    '...PPPCPPPPP....',
    '...PPPPPPPPP....',
    '..PPPPPPPPPPP...',
    '..pPPPPPPPPPp...',
    '.ppPPPPPPPPPpp..',
    '.ppppppppppppp..',
  ] },
  creeper: { pal: { G: '#4fc24f', g: '#2f8f2f', l: '#8de08d' }, px: [
    'GlGGgGGlGGGgGlGG',
    'GGGlGGGGGlGGGGgG',
    'gGKKKKGGGgKKKKGG',
    'GGKKKKlGGGKKKKGl',
    'GlKKKKGGgGKKKKGG',
    'GGKKKKGGGlKKKKGg',
    'GgGGGGKKKKGGlGGG',
    'lGGgGGKKKKGGGGgG',
    'GGGGKKKKKKKKGGGG',
    'GgGGKKKKKKKKGlGG',
    'GGlGKKKKKKKKGGGg',
    'GGGGKKKKKKKKGGGG',
    'gGGGKKGGgGKKGgGG',
    'GGlGKKGGGGKKGGGl',
    'GGGGgGGlGGGGGgGG',
    'GgGGGGGGGgGGlGGG',
  ] },
  steve: { pal: { n: '#4a2f1a', S: '#c99a7a', s: '#a87652', U: '#5a49a8', C: '#2fb8b0', B: '#3a3a9a' }, px: [
    '....nnnnnnnn....',
    '....nnnnnnnn....',
    '....nSSSSSSn....',
    '....SSSSSSSS....',
    '....SWUSSUWS....',
    '....SSSnnSSS....',
    '....SSnsSnSS....',
    '....SSnnnnSS....',
    '..CCCCCCCCCCCC..',
    '..CCCCCCCCCCCC..',
    '..SSCCCCCCCCSS..',
    '..SSCCCCCCCCSS..',
    '..SSBBBBBBBBSS..',
    '....BBBBBBBB....',
    '....BBBBBBBB....',
    '....EEEE.EEEE...',
  ] },
  toad: { px: [
    '.....WWWWWW.....',
    '...WWRRWWRRWW...',
    '..WRRRRWWRRRRW..',
    '.WRRRRWWWWRRRRW.',
    '.WWRRWWWWWWRRWW.',
    'WWWWWWWWWWWWWWWW',
    'WRRWWWWWWWWWWRRW',
    '.WWWWWWWWWWWWWW.',
    '...TTTTTTTTTT...',
    '...TTKTTTTKTT...',
    '...TTKTTTTKTT...',
    '....TTTppTTT....',
    '...BBBBBBBBBB...',
    '..TBBYBBBBYBBT..',
    '...WWWWWWWWWW...',
    '...NN......NN...',
  ] },
  rondoudou: { pal: { b: '#2a9d9d' }, px: [
    '..K..........K..',
    '..KK..pPP...KK..',
    '..KPKPPPPPPKPK..',
    '..KPPPPPPPPPPK..',
    '.KPPPPPpPPPPPPK.',
    '.PPPPPPpPPPPPPP.',
    'PPPPWWPPPPWWPPPP',
    'PPPWbbWPPWbbWPPP',
    'PPPbbbbPPbbbbPPP',
    'PPPbbbbPPbbbbPPP',
    'PPPPbbPPPPbbPPPP',
    'PPPPPPPPPPPPPPPP',
    '.PPPPPPKKPPPPPP.',
    '.PPPPPPPPPPPPPP.',
    '..PPPPPPPPPPPP..',
    '...PPPP..PPPP...',
  ] },
  crewmate: { pal: { L: '#9fe0f0', l: '#5aa8c8' }, px: [
    '....RRRRRR....',
    '...RRRRRRRRR..',
    '..RRRRRRRRRRR.',
    '..RRRLLLLLLLR.',
    '..RRLLWLLLLLLL',
    'rrRRLLLLLLLLLL',
    'rrRRRlllllllR.',
    'rrRRRRRRRRRRR.',
    'rrRRRRRRRRRRR.',
    'rrRRRRRRRRRRR.',
    'rrRRRRRRRRRRR.',
    '..RRRRRRRRRRR.',
    '..RRRRRRRRRRR.',
    '..RRRR...RRRR.',
    '..RRRR...RRRR.',
    '..rrrr...rrrr.',
  ] },

  // ----- Moyen -----
  blinky: { px: [
    '.....RRRR.....',
    '...RRRRRRRR...',
    '..RRRRRRRRRR..',
    '.RRWWRRRRWWRR.',
    '.RWWWWRRWWWWR.',
    '.RWWBBRRWWBBR.',
    'RRWWBBRRWWBBRR',
    'RRRWWRRRRWWRRR',
    'RRRRRRRRRRRRRR',
    'RRRRRRRRRRRRRR',
    'RRRRRRRRRRRRRR',
    'RRRRRRRRRRRRRR',
    'RR.RRR..RRR.RR',
    'R...RR..RR...R',
  ] },
  megaman: { pal: { B: '#2f7cf0', L: '#5fd0ff', b: '#123a8a' }, px: [
    '.....bbbbbb.....',
    '...bbBBLLBBbb...',
    '..bBBBBLLBBBBb..',
    '..bBBBBLLBBBBb..',
    '.bLLBBSSSSBBLLb.',
    '.bLLBSSSSSSBLLb.',
    '.bBBSWWSSWWSBBb.',
    '.bBBSWKSSKWSBBb.',
    '.bBBSSSSSSSSBBb.',
    '..bBSSSKKSSSBb..',
    '...bbSSSSSSbb...',
    '....LLLLLLLL....',
    '..BBLLLLLLLLBB..',
    '.BBBBLLLLLLBBBB.',
    '.BBBBBBBBBBBBBB.',
    '.LLLBBBBBBBBLLL.',
  ] },
  bulbizarre: { pal: { C: '#5cc8a8', c: '#2e8a70', G: '#4caf50', g: '#1f6b3a', l: '#8fdc6a', R: '#d0313d' }, px: [
    '............gg....',
    '..........gGGGg...',
    '.........gGlGGGg..',
    '.C...C..gGlGGGGGg.',
    '.CC.CC..gGGGGGGGg.',
    'CCCCCCCCCgGGGGGg..',
    'CWRCCCWRCCgggggC..',
    'CWWCCCWWCCCCCCCCC.',
    'CCCCCCCCCCcCCcCCC.',
    '.CKCCCCKCCCCCCCCC.',
    '..CCKKKCCCcCCCcCC.',
    '...CCCCCCCCCCCCC..',
    '...CCC.CC..CCC.CC.',
    '...WWW.WW..WWW.WW.',
  ] },
  salameche: { pal: { O: '#ff8c32', D: '#ffe08a' }, px: [
    '....OOOO........',
    '...OOOOOO.......',
    '..OOOOOOOO......',
    '..OOKWOOOOO.....',
    '..OOKKOOOOO.....',
    '.OOOOOOOOOO.....',
    '.OOOOOOOOOO..R..',
    '..OKOOOOOO..RYR.',
    '...OOOOOOO..RYR.',
    '..OOODDDOOO..O..',
    '.OO.ODDDDOO.OO..',
    '....ODDDDOOOO...',
    '....OODDOOOO....',
    '....OOOOOOO.....',
    '...OOO..OOO.....',
    '..WOO....OOW....',
  ] },
  carapuce: { pal: { L: '#78c8f0', N: '#a0581e', T: '#f5e0a0', r: '#8a3a2a' }, px: [
    '....LLLLL.......',
    '...LLLLLLLL.....',
    '..LLLLLLLLLL....',
    '..LLWrLLLWrL....',
    '..LLrrLLLrrL....',
    '..LLLLLLLLLL....',
    '...LLKKKKLL.....',
    '...NTTTTTTN.....',
    '.LLNTTTTTTNLL...',
    'LL.NTTTTTTN.LL..',
    '...NTTTTTTNN.LL.',
    '...NNTTTTNNNLLL.',
    '....LLL..LLL.LL.',
    '...LLLL..LLLL...',
  ] },
  wario: { pal: { Y: '#ffd22a', U: '#7a3fb0', P: '#ff8fb8', B: '#2f54d6' }, px: [
    '....YYYYYY......',
    '..YYYYYYYYYY....',
    '..YYYWBWYYYYY...',
    '.YYYYWWWYYYYYY..',
    '..nnSSSSKSSn....',
    '.nSSSSSSKSSSnn..',
    '.nSSSSSPPPPS....',
    '..SKKKKPPPPKK...',
    '...SSKSKSKSS....',
    '...SSSWWWWSS....',
    '....SSSSSSS.....',
    '..YYUUUUUUYY....',
    '.YYUYUUUUYUYY...',
    '.SSUUUUUUUUSS...',
    '...UUU..UUU.....',
    '..NNNN..NNNN....',
  ] },
  waluigi: { pal: { U: '#6a2fa0', u: '#2b1a40', Y: '#ffd22a' }, px: [
    '....UUUUUU.....',
    '..UUUUUUUUUU...',
    '..UUUYYYUUUUU..',
    '.UUUUUYUUUUUUU.',
    '..nnSSSSKSSn...',
    '..nSSSSSKSSSn..',
    '..nSSSSPPPPS...',
    '...SKKKKKKKKK..',
    '...SSSSSSSSS...',
    '....SSSSSSS....',
    '...UUuuuuuUU...',
    '..UUUuuuuuUUU..',
    '..WWuuuuuuuWW..',
    '....uuu.uuu....',
    '....uuu.uuu....',
    '...OOOO.OOOO...',
  ] },
  crash: { pal: { O: '#f07a1a', G: '#3fb04f', T: '#f2c48a' }, px: [
    '....OO..OO......',
    '...OOOOOOOO.....',
    '..OOOOOOOOOO....',
    '..OnnOOOOnnO....',
    '.OWWGOOOOWGWO...',
    '.OWWKOOOOWKWO...',
    '.OOOOOOKKOOOO...',
    '.OOTTTTKKTTTTO..',
    '..TTKKKKKKKTT...',
    '..TTKWWWWWKTT...',
    '...TTKKKKKTT....',
    '....TTTTTTT.....',
    '...BBBBBBBB.....',
    '..OBBBBBBBBO....',
    '..OBBBBBBBBO....',
    '...BBB..BBB.....',
  ] },
  rayman: { pal: { U: '#7a3fc0', Y: '#ffcf2a', S: '#f5c8a0' }, px: [
    '......YY........',
    '.....YYYY.......',
    '....YYYYY.......',
    '...YYSSSSY......',
    '...SSWKWKS......',
    '...SSSSSSS......',
    '...SSSPPSSS.....',
    '....SSSSSS......',
    '................',
    '.WW..RRRRR...WW.',
    'WWWW.UUWUU..WWWW',
    '.WW..UUUUU...WW.',
    '.....UUUUU......',
    '................',
    '....YYY..YYY....',
    '...YYYY..YYYY...',
  ] },
  bomberman: { pal: { S: '#ffc0b0', P: '#ff5d9a', B: '#3050d0' }, px: [
    '......PPP.......',
    '.......K........',
    '....WWWWWWWW....',
    '...WWWWWWWWWW...',
    '..WWSSSSSSSSWW..',
    '.PWSSKSSSSKSSWP.',
    '.PWSSKSSSSKSSWP.',
    '..WSSSSSSSSSSW..',
    '...WWWWWWWWWW...',
    '...BBBBYBBBB....',
    '..WBBBBBBBBBW...',
    '..WWBBBBBBBWW...',
    '....BBBBBBB.....',
    '....PP...PP.....',
    '...PPP...PPP....',
  ] },
  knuckles: { pal: { R: '#d8282c', r: '#8c1416', W: '#ffffff', G: '#2a9a3a' }, px: [
    'RR..RRRRRR......',
    '.RRRRRRRRRRR....',
    '..RRRRRRRRRRR...',
    'RRRRRRRRWWWRW...',
    '.RRRRRRRWWGWGW..',
    'RRRRRRRRSSSSSS..',
    '..RRRRRSSSSSSK..',
    '.RRRRRRRSSSSSS..',
    'RR..RRRRRRRR....',
    '...RRWWWWWRR....',
    '.WWWRRWWWRRWWW..',
    'WWWWWRRRRRWWWWW.',
    '.WWW.RRRRRR.WWW.',
    '.....RR..RR.....',
    '....GGG..GGG....',
    '...GGGG..GGGG...',
  ] },
  tails: { pal: { O: '#ffa020', W: '#ffffff' }, px: [
    '....O......O....',
    '...OOO....OOO...',
    '..OOWOOOOOOWOO..',
    '..OOOOOOOOOOOO..',
    '.OOOWWWOOWWWOOO.',
    '.OOOWBKOOWBKOOO.',
    'OOOOWWWOOWWWOOOO',
    '.OOWWWWKKWWWWOO.',
    '..WWWWWWWWWWWW..',
    '...WWWWWWWWWW...',
    '....OOWWWWOO....',
    'OO..OOWWWWOO..OO',
    'OOO.OOOOOOOO.OOO',
    'WWOOOOO..OOOOOWW',
    '.WWO.RR..RR.OWW.',
    '....RRRR.RRRR...',
  ] },
  samus: { pal: { O: '#f07020', R: '#c8281e', Y: '#ffd040', G: '#3fe060', g: '#1a8a3a' }, px: [
    '.....RRRRRR.....',
    '...RRRRRRRRRR...',
    '..RRORRRRRRORR..',
    '..RRgGGGGGGgRR..',
    '.RROGGGGGGGGORR.',
    '.RROgGGGGGGgORR.',
    '.RRORggggggRORR.',
    '..RRRRRRRRRRRR..',
    'YYYY.RRYYRR.YYYY',
    'YOOYYOOYYOOYYOOY',
    'YOOOYOOOOOOYOOOY',
    'YYYYRROOOORRYYYY',
    '.RRRRRROORRRRRR.',
    '.EEE.RRRRRR.RRR.',
    '.EEE.OOOOOO.RRR.',
    '.ee..RR..RR..RR.',
  ] },
  lapincretin: { pal: { P: '#ffb0c8', W: '#f6f6f6', E: '#d0d0d0' }, px: [
    '..WW......WW....',
    '..WP......PW....',
    '..WP......PW....',
    '..WP......PW....',
    '..WW......WW....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    'WWKKWWWWWWKWWW..',
    'WWKKWWWWWWWWWW..',
    'WWWWWWWWWWWWWW..',
    'WWrrrrrrrrrrWW..',
    'WWrWWrrrrWWrWW..',
    'WWrrrrPPrrrrWW..',
    '.WWrrrPPrrrWW...',
    '..WWWWWWWWWW....',
    '.EWWWWWWWWWWE...',
    '..WWW....WWW....',
  ] },
  ectoplasma: { pal: { U: '#6a4aa8', u: '#3e2a70' }, px: [
    '.U.....U......U.',
    '.UU...UUU....UU.',
    '.UUU.UUUUU..UUU.',
    '..UUUUUUUUUUUU..',
    '.UUUUUUUUUUUUUU.',
    'UUURRUUUUUURRUUU',
    'UUUURRUUUURRUUUU',
    'UUUUUUUUUUUUUUUU',
    'UUWWWWWWWWWWWWUU',
    'UUWKWKWKWKWKWWUU',
    'UUUWWWWWWWWWWUUU',
    'UUUUUWWWWWWUUUUU',
    '.UUUUUUUUUUUUUU.',
    '..UUUUUUUUUUUU..',
    '...UUU....UUU...',
    '..UUUU....UUUU..',
  ] },
  ronflex: { pal: { c: '#2a6a78', T: '#f2e0b0' }, px: [
    '...c........c...',
    '...cc.cccc.cc...',
    '...ccccccccccc..',
    '..ccTTTTTTTTcc..',
    '..cTTKKTTKKTTc..',
    '..cTTTTTTTTTTc..',
    '..cTTWKKKKWTTc..',
    '.cccTTTTTTTTccc.',
    'cccTTTTTTTTTTccc',
    'ccTTTTTTTTTTTTcc',
    'ccTTTTTTTTTTTTcc',
    'cTTTTTTTTTTTTTTc',
    'cTTTTTTTTTTTTTTc',
    '.ccTTTTTTTTTTcc.',
    'TTTTc......cTTTT',
    'TKTTT......TTTKT',
  ] },
  boo: { pal: { W: '#f4f4f4', E: '#c8c8d8' }, px: [
    '.....WWWWWW.....',
    '...WWWWWWWWWW...',
    '..WWWWWWWWWWWW..',
    '.WWWWKWWWWKWWWW.',
    '.WWWWKWWWWKWWWW.',
    'WWWWWKWWWWKWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWKKKKKKKKKKWWW',
    'WWWKWKRRRRKWKWWW',
    'WWWWKKRRRRKKWWWW',
    'EWWWWWKRRKWWWWWE',
    'EEWWWWWWWWWWWWEE',
    '.EWWWWWWWWWWWWE.',
    '..EWWWWWWWWWWE..',
    '...EEWWWWWWEE...',
    '.....EEEEEE.....',
  ] },
  goomba: { pal: { N: '#a0501e', T: '#f2c890' }, px: [
    '......NNNN......',
    '.....NNNNNN.....',
    '....NNNNNNNN....',
    '...NNNNNNNNNN...',
    '..NNKKNNNNKKNN..',
    '.NNNNKKNNKKNNNN.',
    '.NNNWKNNNNKWNNN.',
    'NNNNWKNNNNKWNNNN',
    'NNNNWWNNNNWWNNNN',
    'NNNNNNNNNNNNNNNN',
    '.NNNNTTTTTTNNNN.',
    '....TTTTTTTT....',
    '....TTTTTTTT....',
    '..KKKTTTTTTKKK..',
    '.KKKKKK..KKKKKK.',
    '.KKKKK....KKKKK.',
  ] },
  masterchief: { pal: { G: '#5a7a3a', g: '#3a5226', A: '#f0a020', Y: '#ffd060' }, px: [
    '.....GGGGGG.....',
    '...GGGGGGGGGG...',
    '..GGGGGGGGGGGG..',
    '..GGAAAAAAAAGG..',
    '.GGAYYAAAAAAAGG.',
    '.GGAAAAAAAAAAGG.',
    '.GGGAAAAAAAAGGG.',
    '..GGGGGGGGGGGG..',
    '..gGGGeeeeGGGg..',
    '.ggGGGeeeeGGGgg.',
    'GGGGGGGGGGGGGGGG',
    'GGgGGGGGGGGGGgGG',
    'GGgggGGGGGGgggGG',
    'GG.ggGGGGGGgg.GG',
    'ee..eeeeeeee..ee',
    '....GGG..GGG....',
  ] },
  mspacman: { px: [
    '.R.R..YYYYY..',
    'RRRRRYYYYYYY.',
    '.RBRYYYYYYYYY',
    'RRRRYYYKYYY..',
    '.YYYYYYYYY...',
    'YYYYYYYY.....',
    'YYYYYY.......',
    'YYYYRR.......',
    'YYYYYYYY.....',
    '.YYYYYYYYY...',
    '.YYYYYYYYYYY.',
    '..YYYYYYYYY..',
    '....YYYYY....',
  ] },
  shyguy: { pal: { R: '#e02828', W: '#f6f6f6' }, px: [
    '....RRRRRR.....',
    '..RRRRRRRRRR...',
    '.RRRWWWWWWRRR..',
    '.RRWWWWWWWWRR..',
    'RRWWKKWWKKWWRR.',
    'RRWWKKWWKKWWRR.',
    'RRWWWWWWWWWWRR.',
    'RRWWWWKKWWWWRR.',
    '.RRWWWKKWWWRR..',
    '.RRRWWWWWWRRR..',
    'RRRRRRRRRRRRRR.',
    'RRRRRKKKKRRRRR.',
    '.RRRRRRRRRRRR..',
    '.RRRRRRRRRRRR..',
    '..BBBB..BBBB...',
    '..BBBB..BBBB...',
  ] },
  ryu: { pal: { W: '#f2f2f2', E: '#c8c8c8', R: '#e02020' }, px: [
    '.....nnnnnn......',
    '....nnnnnnnn.....',
    '...RRRRRRRRRR.RR.',
    '...nnSSSSSSnnRR..',
    '...nSKKSSKKSn....',
    '...SSSSSSSSSS....',
    '....SSSnnSSS.....',
    '....SSSSSSSS.....',
    '..WWWWSSSSWWWW...',
    '.WWWWWWSSWWWWWW..',
    'SSWWWWWSSWWWWWSS.',
    'SSEWWWWWWWWWWESS.',
    '...KKKKKKKKKK....',
    '...WWWWK.WWWW....',
    '...WWWW..WWWW....',
    '...SSSS..SSSS....',
  ] },
  spyro: { pal: { U: '#8a3ad0', u: '#5a1f90', Y: '#ffc830', G: '#3cc860' }, px: [
    '..Y..........Y..',
    '..YY........YY..',
    '...YY......YY...',
    '....YUUUUUUY....',
    '...UUUUUUUUUU...',
    '..UUWGUUUUWGUU..',
    '..UUWKUUUUWKUU..',
    'Y.UUUUUUUUUUUU.Y',
    'YYUUUUUUUUUUUUYY',
    '.YYUUUKUUKUUUYY.',
    '..UUUUUUUUUUUU..',
    '...UUuuuuuuUU...',
    '.YYUUYYYYYYUUYY.',
    'YYYUUYYYYYYUUYYY',
    '....UUU..UUU....',
    '...UUUU..UUUU...',
  ] },

  // ----- Difficile -----
  qbert: { pal: { O: '#ff7a1a', o: '#c04a00' }, px: [
    '....OOOOOO.......',
    '..OOOOOOOOOO.....',
    '.OOOOOOOOOOOO....',
    '.OOWWWOOWWWOO....',
    'OOWWWKOWWWKWO....',
    'OOWWKKOWWKKWOO...',
    'OOOWWWOOWWWOOOOOO',
    'OOOOOOOOOOOOOOOOK',
    'OOOOOOOOOOOOOOOOK',
    '.OOOOOOOOOOOOOOO.',
    '..OOOOOOOOOOO....',
    '....OOOOOOO......',
    '.....oo..oo......',
    '.....oo..oo......',
    '...ooo..ooo......',
  ] },
  pooka: { pal: { R: '#e8382a', Y: '#ffd800' }, px: [
    '....RRRRRRR.....',
    '..RRRRRRRRRRR...',
    '.RRRRRRRRRRRRR..',
    '.RYYYYYYYYYYYR..',
    'RRYWWKYYYWWKYRR.',
    'RRYWWKYYYWWKYRR.',
    'RRYYYYYYYYYYYRR.',
    'RRRRRRRRRRRRRRR.',
    'RRRRRRRRRRRRRRR.',
    '.RRRRRRRRRRRRR..',
    '..RRRRRRRRRRR...',
    '...WW.....WW....',
    '..WWW.....WWW...',
  ] },
  bub: { pal: { G: '#3ad04a', g: '#1e8a2a', T: '#f8e8a0', W: '#ffffff' }, px: [
    '..W..W..........',
    '..WWWWWGGGGG....',
    '..WWWWGGGGGGGG..',
    '..GGGGGWWWGWWWG.',
    '.GGGGGGWKWGWKWG.',
    'WWGGGGGWKWGWKWG.',
    '.GGGGGGGGGGGGGGG',
    'WWGGGGGGGGGGKGGK',
    '.GGGGGGTTTTTTTT.',
    '..GGGGTTTTTTTT..',
    '..GGGTTTTTT.....',
    '.GGGGTTTTTT.....',
    'GGGGGTTTTTT.....',
    '.GGGGGTTTTGG....',
    '..GGGGGGGGGG....',
    '..OOOO..OOOO....',
  ] },
  alexkidd: { pal: { S: '#f5b88a', R: '#e02828', n: '#2a1a10' }, px: [
    '.....nnnnnn.....',
    '...nnnnnnnnnn...',
    '..nnnnnnnnnnnn..',
    '..nnSSSSSSSSnn..',
    'SSnSSKSSSSKSSnSS',
    'SSSSSKSSSSKSSSSS',
    'SSSSSSSSSSSSSSSS',
    '.S.SSSSSSSSSS.S.',
    '....SSSRRSSS....',
    '.....SSSSSS.....',
    '...RRRRYRRRR....',
    '..RRRRRRRRRRR...',
    '..SRRRRRRRRRS...',
    '...RRRRRRRRR....',
    '...RRR...RRR....',
    '..YYYY...YYYY...',
  ] },
  ness: { pal: { R: '#e02838', B: '#2848c8', Y: '#ffd830', n: '#2a1a10' }, px: [
    '.....RRRRRR.....',
    '....RRRRRRRR....',
    '...RRRRRRRRRR...',
    '...RRRRRRRRRRBBB',
    '...nnnnnnnnnBBBB',
    '...nSSSSSSSSn...',
    '...SSKSSSSKSS...',
    '...SSSSSSSSSS...',
    '....SSSnnSSS....',
    '..BBBBBBBBBBBB..',
    '..YYYYYYYYYYYY..',
    '.SBBBBBBBBBBBBS.',
    '.SYYYYYYYYYYYYS.',
    '...BBBBBBBBBB...',
    '...BBBB..BBBB...',
    '..RRRR....RRRR..',
  ] },
  earthwormjim: { pal: { P: '#f2a0a8', M: '#e8e8f0', E: '#a8a8b8', R: '#c82020' }, px: [
    '......PPPP......',
    '.....PPPPPP.....',
    '....PWWPPWWP....',
    '....PWKPPWKP....',
    '....PWWPPWWP....',
    '.....PPPPPP.....',
    '.....PKKKKP.....',
    '......PPPP......',
    '...MMMMPPMMMM...',
    '..MMMMMMMMMMMM..',
    'eeMMEMMMMMMEMM..',
    'eeeeEMMRRMMEMMR.',
    'ee..EMMMMMMEMMRR',
    '....MMMMMMMM..R.',
    '....MMM..MMM....',
    '...EEEE..EEEE...',
  ] },
  sackboy: { pal: { N: '#c89a5a', n: '#8a6030', s: '#a87a40' }, px: [
    '.....NNNNNN.....',
    '...NNNNNNNNNN...',
    '..NNsNNNNNNsNN..',
    '.NNNNNNNNNNNNNN.',
    '.NNNKKNNNNKKNNN.',
    '.NNNKKNNNNKKNNN.',
    '.NNNNNNNNNNNNNN.',
    '.NNNKNNNNNNKNNN.',
    '..NNNKKKKKKNNN..',
    '...NNNNNNNNNN...',
    '.....nNNNNn.....',
    '...NNNNEENNNN...',
    '..NNNNNEENNNNN..',
    '..NN.NNEENN.NN..',
    '.....NNNNNN.....',
    '....NNN..NNN....',
  ] },
  chunli: { pal: { B: '#2050c8', b: '#10287a', n: '#2a1a10', Y: '#ffd040', W: '#f4f4f4' }, px: [
    '.WWW........WWW.',
    'WnnnW......WnnnW',
    'WnnnWnnnnnnWnnnW',
    '.WWWnnnnnnnnWWW.',
    '...nnSSSSSSnn...',
    '...nSKSSSSKSn...',
    '...SSSSSSSSSS...',
    '....SSSRRSSS....',
    '.....SSSSSS.....',
    '..BBBBBYYBBBBB..',
    '.YBBBBBYYBBBBBY.',
    'SSBBBBBYYBBBBBSS',
    'SS.BBBBBBBBBB.SS',
    '....BBB..BBB....',
    '....SSS..SSS....',
    '...WWWW..WWWW...',
  ] },
  kratos: { pal: { S: '#e8e0d8', R: '#c81818', n: '#2a2020' }, px: [
    '.....SSSSSS.....',
    '...SSSSRSSSSS...',
    '..SSSSSRSSSSSS..',
    '..SSSSSRSSSSSS..',
    '..SnnSSRSSnnSS..',
    '..SSKSSRSSKSSS..',
    '..SSSSSRSSSSSS..',
    '..SSSnnnnnnSSS..',
    '...nnnnnnnnnn...',
    '...nnnSSSSnnn...',
    '....nnnnnnnn....',
    '..RSSSSSSSSSSS..',
    '.RRSSSSSSSSSSSS.',
    'RRSSSSRRSSSSSSSS',
    'SSSSSRRSSSSSS.SS',
    'SS..NNNNNNNN..SS',
  ] },
  cuphead: { pal: { R: '#d82020', W: '#f6f6f6', E: '#c8c8d0' }, px: [
    '......RRR.......',
    '.......RRRR.....',
    '..EWWWWWRWWWWE..',
    '..EKKKKKRKKKKE..',
    '..EWWWWWWWWWWE..',
    '..WWWKKWWKKWWW..',
    '..WWWKWWWKWWWW..',
    '..WWWWWRRWWWWW..',
    '...WWKWWWWKWW...',
    '...WWWKKKKWWW...',
    '....WWWWWWWW....',
    '...EKKKKKKKKE...',
    '..WWKKKKKKKKWW..',
    '....RRRRRRRR....',
    '....RRR..RRR....',
    '...KKKK..KKKK...',
  ] },
  shovelknight: { pal: { B: '#3070e0', L: '#80c8ff', b: '#183c8a', Y: '#ffd040' }, px: [
    'Y............Y.',
    'YY..........YY.',
    '.YY.BBBBBB.YY..',
    '..YBBBBBBBBY...',
    '..BBBBBBBBBB...',
    '..BBKKKKKKBB.E.',
    '..BBKBBBBKBB.E.',
    '..BBKKKKKKBB.E.',
    '...BBBBBBBB..E.',
    '.LLBBBBBBBBLLE.',
    'LLBBBBBBBBBBLE.',
    'LLBBBbbbbBBBLE.',
    '..BBBBBBBBBB.E.',
    '..BBBB..BBBB.EE',
    '..bbbb..bbbb.EE',
  ] },
  slime: { pal: { L: '#4a9cf0', B: '#2060c0', W: '#e0f0ff' }, px: [
    '.......L........',
    '.......LL.......',
    '......LLLL......',
    '.....LLLLLL.....',
    '....LLLLLLLL....',
    '...LWLLLLLLLL...',
    '..LWLLLLLLLLLL..',
    '.LLLLWKLLWKLLLL.',
    '.LLLLKKLLKKLLLL.',
    'LLLLLLLLLLLLLLLL',
    'LLLLKRRRRRRKLLLL',
    'LLLLLKRRRRKLLLLL',
    'BLLLLLKKKKLLLLLB',
    '.BBLLLLLLLLLLBB.',
    '...BBBBBBBBBB...',
  ] },
  chocobo: { pal: { Y: '#ffd030', A: '#e8a010', O: '#ff9020' }, px: [
    '.....Y.Y.......',
    '....YYYYY......',
    '...YYYYYYY.....',
    '..YYYWKYYYY....',
    '..YYYKKYYYOOO..',
    '..YYYYYYYYOOOO.',
    '...YYYYYYYOO...',
    '....YYYYYY.....',
    '....YYYYYY...A.',
    '...YYYYYYYYYAA.',
    '..YYYYYYYYYYYA.',
    '..YYYYYYYYYYY..',
    '...YYYYYYYYY...',
    '.....OO..OO....',
    '.....OO..OO....',
    '....OOO.OOO....',
  ] },
  isabelle: { pal: { Y: '#ffd860', A: '#e8b030', R: '#e04040', G: '#3a9a5a', W: '#fbfbfb' }, px: [
    '.......RR.......',
    '......RYYR......',
    '.......YY.......',
    '.AA..YYYYYY..AA.',
    'AAAYYYYYYYYYYAAA',
    'AAYYYYYYYYYYYYAA',
    'AA.YYKYYYYKYY.AA',
    '...YYKYYYYKYY...',
    '...YYYWWWWYYY...',
    '....YWWKKWWY....',
    '.....WWWWWW.....',
    '....GGRRRRGG....',
    '...GGGWWWWGGG...',
    '...GGGWWWWGGG...',
    '...GGGGGGGGGG...',
    '....YY....YY....',
  ] },
  pikmin: { pal: { R: '#e83030', G: '#3ab040', l: '#8ae060' }, px: [
    '.......Ell......',
    '.......E.lll....',
    '.......E..ll....',
    '.......E........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...RRRRRRRRR....',
    '...RWWRRRWWR....',
    '...RWKRRRWKR....',
    '...RRRRRRRRR....',
    '....RRRRRRR.....',
    '......RRR.......',
    '....RRRRRRR.....',
    '...R.RRRRR.R....',
    '.....RR.RR......',
    '.....RR.RR......',
  ] },
  frogger: { pal: { G: '#3ac83a', g: '#1e7a1e', Y: '#ffd800', R: '#e02828' }, px: [
    '..GG........GG..',
    '.GGGG......GGGG.',
    '..GG..WWWW..GG..',
    '...GGWKKKKWGG...',
    '....GGGGGGGG....',
    '...GGgGGGGgGG...',
    '..GGGGYGGYGGGG..',
    '..GGgGGGGGGgGG..',
    '..GGGGgGGgGGGG..',
    '...GGGGGGGGGG...',
    '..GGGGGGGGGGGG..',
    '.GGGG......GGGG.',
    '.GG..........GG.',
    'GGGG........GGGG',
  ] },
  gamewatch: { px: [
    '.....KKKK.......',
    '....KKKKKK......',
    '...KKKKKKKK.....',
    '...KKKKKKKKKK...',
    '...KKKKKKKKKK...',
    '....KKKKKKK.....',
    '.....KKKKK......',
    '.K....KKK....K..',
    '..K..KKKKK..K...',
    '...KKKKKKKKK....',
    '.....KKKKK......',
    '.....KKKKK......',
    '.....KKKKK......',
    '....KK...KK.....',
    '...KK.....KK....',
    '..KKK.....KKK...',
  ] },
  metroid: { pal: { G: '#7af06a', l: '#c8ffb0', R: '#e03050', r: '#a01838', W: '#fff0f0' }, px: [
    '....llllllll....',
    '..llGGGGGGGGll..',
    '.lGGGGGGGGGGGGl.',
    'lGGGRRGGGGRRGGGl',
    'lGGRrRGGGGRrRGGl',
    'lGGGRRGGRRGGGGGl',
    'lGGGGGGRrRGGGGGl',
    '.lGGGGGGRRGGGGl.',
    '..llllllllllll..',
    '..WW.WW..WW.WW..',
    '..W...W..W...W..',
    '.WW...WW.W...WW.',
    '..W..W....W..W..',
  ] },
  hollowknight: { pal: { W: '#f4f4f8', b: '#2a3050', B: '#3a4a78' }, px: [
    '.W..........W...',
    '.WW........WW...',
    '..WW......WW....',
    '..WWWWWWWWWW....',
    '.WWWWWWWWWWWW...',
    '.WWKKKWWKKKWW...',
    '.WWKKKWWKKKWW...',
    '.WWKKKWWKKKWW...',
    '..WWWWWWWWWW....',
    '...WWWWWWWW.....',
    '..bbbbbbbbbb....',
    '.bbbbbbbbbbbb...',
    'bbbBbbbbbbBbbb..',
    'bbbbbbbbbbbbbb..',
    '.bbbbbbbbbbbb...',
    '..bb.bbbb.bb....',
  ] },
  lemming: { pal: { G: '#3ad040', B: '#3048e0', S: '#ffc8a0' }, px: [
    '...GGGG.....',
    '..GGGGGGG...',
    '.GGGGGGGG...',
    '.GGGSSSS....',
    '..GGSKSS....',
    '...SSSSS....',
    '....BBB.....',
    '...BBBBB....',
    '..SBBBBBS...',
    '...BBBBB....',
    '...BBBBB....',
    '...SS.SS....',
    '..SSS.SSS...',
  ] },
  pit: { pal: { W: '#fafafa', E: '#d0d0e0', n: '#5a3418', G: '#5ab040', Y: '#ffd040' }, px: [
    '......GGGGG.....',
    '....GGnnnnnGG...',
    '...GnnnnnnnnnG..',
    'W..nnnSSSSnnn..W',
    'WW.nSSBSSBSSn.WW',
    'WWWSSSSSSSSSSWWW',
    'WWWWSSSSSSSSWWWW',
    'EWWW..SSSS..WWWE',
    '.EWWWWWWWWWWWWE.',
    '..EWWWWYWWWWWE..',
    '...WWWWWWWWWW...',
    '..SWWWWWWWWWWS..',
    '...WWWWWWWWWW...',
    '....SSS..SSS....',
    '....nnn..nnn....',
  ] },
  inkling: { pal: { O: '#ff8a1e', o: '#d05a00', K: '#1a1a2a' }, px: [
    '....OOOOOOOO....',
    '..OOOOOOOOOOOO..',
    '.OOOOOOOOOOOOOO.',
    '.OOOSSSSSSSSOOO.',
    'OOKKKKKKKKKKKKOO',
    'OOKWWKKKKKKWWKOO',
    'OOKWKKSSSSKKWKOO',
    'OOSSSSSSSSSSSSOO',
    'OO.SSSSSSSSSS.OO',
    'Oo..SSSRRSSS..oO',
    'o.....SSSS.....o',
    '....CCCCCCCC....',
    '...CCCCCCCCCC...',
    '...SCCCCCCCCS...',
    '....KKK..KKK....',
    '...WWWW..WWWW...',
  ] },
};

function resolve(id) {
  const s = SPRITES[id];
  if (!s) throw new Error('Sprite inconnu : ' + id);
  const base = s.like ? SPRITES[s.like] : s;
  const px = base.px;
  const pal = { ...PALETTE, ...(base.pal || {}), ...(s.like ? s.pal || {} : {}) };
  const used = {};
  for (const row of px) for (const ch of row) if (ch !== '.') used[ch] = pal[ch];
  return { w: Math.max(...px.map(r => r.length)), h: px.length, px, pal: used };
}

module.exports = { PALETTE, SPRITES, resolve };
