// Questions de démonstration du Grand Sondage (format d'import). Lancé par scripts/sondage-import.js --demo.
// Format compact : [réponse, votes, 'variante|variante|…'] → converti au format JSON standard.
const Q = (question, category, difficulty, answers) => ({
  question, category, difficulty, language: 'fr', active: true,
  answers: answers.map(([answer, votes, variants = ''], i) => ({ answer, votes, position: i + 1, accepted_variants: variants ? variants.split('|') : [] })),
});

module.exports = [
  Q('Citez quelque chose que les gens oublient souvent avant de partir en vacances.', 'Vacances', 'facile', [
    ['Chargeur de téléphone', 38, 'chargeur|chargeur téléphone|chargeur de portable|câble'],
    ['Brosse à dents', 24, 'dentifrice|trousse de toilette'],
    ['Passeport', 18, "papiers|carte d'identité|pièce d'identité|papiers d'identité"],
    ['Lunettes de soleil', 12, 'lunettes|solaires'],
    ['Médicaments', 8, 'médocs|traitement|pilules'],
  ]),
  Q('Citez quelque chose que les gens font avant de dormir.', 'Vie quotidienne', 'facile', [
    ['Se brosser les dents', 42, 'brosser les dents|dents|brosse à dents'],
    ['Regarder son téléphone', 31, 'téléphone|scroller|réseaux sociaux|regarder son portable'],
    ['Lire', 15, 'lire un livre|livre|lecture'],
    ['Mettre son pyjama', 8, 'pyjama|se changer|se déshabiller'],
    ['Aller aux toilettes', 4, 'toilettes|pipi|faire pipi|wc'],
  ]),
  Q('Citez un animal que l’on trouve dans une ferme.', 'Animaux', 'facile', [
    ['Vache', 35, 'veau|taureau|bœuf'],
    ['Poule', 25, 'coq|poulet|poussin'],
    ['Cochon', 18, 'porc|truie|cochonnet'],
    ['Mouton', 12, 'brebis|agneau'],
    ['Cheval', 6, 'jument|poney|âne'],
    ['Chèvre', 4, 'bouc|biquette'],
  ]),
  Q('Citez un plat typiquement français.', 'France', 'moyen', [
    ['Bœuf bourguignon', 26, 'bourguignon'],
    ['Raclette', 18, ''],
    ['Blanquette de veau', 15, 'blanquette'],
    ['Pot-au-feu', 12, 'pot au feu'],
    ['Croque-monsieur', 10, 'croque monsieur|croque'],
    ['Escargots', 9, 'escargot de bourgogne'],
    ['Cassoulet', 6, ''],
    ['Ratatouille', 4, ''],
  ]),
  Q('Citez quelque chose que l’on trouve dans un frigo.', 'Nourriture', 'facile', [
    ['Lait', 30, 'bouteille de lait'],
    ['Beurre', 22, ''],
    ['Fromage', 20, 'camembert|emmental|gruyère'],
    ['Œufs', 14, 'oeuf|boîte d’œufs'],
    ['Yaourts', 8, 'yaourt|yogourt|yoghourt'],
    ['Légumes', 6, 'salade|carottes|tomates'],
  ]),
  Q('Citez une excuse pour arriver en retard au travail.', 'Travail', 'moyen', [
    ['Les bouchons', 32, 'embouteillages|trafic|circulation|bouchon'],
    ['Le réveil n’a pas sonné', 25, 'réveil|panne de réveil|pas entendu le réveil'],
    ['Grève des transports', 16, 'grève|train en retard|bus en retard|métro|retard de train'],
    ['Un enfant malade', 11, 'enfant malade|les enfants|école|crèche'],
    ['Une panne de voiture', 9, 'panne|voiture en panne|crevaison|pneu crevé'],
    ['Un rendez-vous médical', 7, 'médecin|dentiste|rendez-vous'],
  ]),
  Q('Citez une matière que l’on étudie à l’école.', 'École', 'facile', [
    ['Mathématiques', 40, 'maths|math'],
    ['Français', 25, ''],
    ['Histoire-géographie', 15, 'histoire|géographie|histoire géo|géo'],
    ['Anglais', 10, 'langues|langue vivante'],
    ['Sport', 6, 'eps|éducation physique|gym'],
    ['Sciences', 4, 'svt|physique|chimie|physique chimie|biologie'],
  ]),
  Q('Citez un sport que l’on peut regarder à la télévision.', 'Sport', 'facile', [
    ['Football', 45, 'foot|soccer'],
    ['Rugby', 18, ''],
    ['Tennis', 14, 'roland garros'],
    ['Cyclisme', 10, 'vélo|tour de france'],
    ['Formule 1', 8, 'f1|course automobile|course de voitures'],
    ['Basket', 5, 'basketball|basket ball|nba'],
  ]),
  Q('Citez un objet que l’on a toujours dans son sac ou dans ses poches.', 'Vie quotidienne', 'moyen', [
    ['Téléphone', 34, ''],
    ['Clés', 28, 'clé|clefs|trousseau'],
    ['Portefeuille', 18, 'porte monnaie|porte-monnaie|carte bleue|carte bancaire|argent'],
    ['Mouchoirs', 9, 'mouchoir|kleenex'],
    ['Écouteurs', 6, 'casque|airpods'],
    ['Rouge à lèvres', 5, 'baume à lèvres|maquillage|stick à lèvres'],
  ]),
  Q('Citez quelque chose que les enfants demandent au supermarché.', 'Enfants', 'moyen', [
    ['Des bonbons', 36, 'bonbon|friandises|sucreries'],
    ['Des jouets', 22, 'jouet|un jouet'],
    ['Du chocolat', 15, 'kinder|œuf en chocolat'],
    ['Des gâteaux', 12, 'biscuits|gâteau'],
    ['Des céréales', 8, 'céréale'],
    ['Une glace', 7, 'glaces'],
  ]),
  Q('Citez un film d’animation que tout le monde connaît.', 'Cinéma', 'moyen', [
    ['Le Roi Lion', 30, 'roi lion'],
    ['La Reine des neiges', 22, 'reine des neiges|frozen'],
    ['Toy Story', 16, ''],
    ['Shrek', 13, ''],
    ['Le Monde de Nemo', 9, 'nemo|monde de nemo'],
    ['Ratatouille', 6, ''],
    ['Les Indestructibles', 4, 'indestructibles'],
  ]),
  Q('Citez un instrument de musique.', 'Musique', 'facile', [
    ['Guitare', 34, 'guitare électrique'],
    ['Piano', 30, 'clavier|synthé'],
    ['Batterie', 14, 'tambour|percussions'],
    ['Violon', 12, ''],
    ['Flûte', 6, 'flûte à bec|flûte traversière'],
    ['Trompette', 4, ''],
  ]),
  Q('Citez un jeu vidéo ou une série de jeux vidéo célèbre.', 'Jeux vidéo', 'difficile', [
    ['Mario', 28, 'super mario|mario kart|mario bros'],
    ['Fortnite', 17, ''],
    ['Minecraft', 15, ''],
    ['Pokémon', 12, 'pokemon'],
    ['FIFA', 9, 'ea sports fc|fc 24|foot'],
    ['Tetris', 7, ''],
    ['Call of Duty', 6, 'cod'],
    ['Zelda', 6, 'the legend of zelda|legend of zelda'],
  ]),
  Q('Citez une application que l’on ouvre tous les jours sur son téléphone.', 'Technologie', 'moyen', [
    ['WhatsApp', 30, 'whats app|whatsapp'],
    ['Instagram', 20, 'insta'],
    ['Messages', 15, 'sms|textos'],
    ['YouTube', 12, 'you tube'],
    ['TikTok', 10, 'tik tok'],
    ['Mails', 8, 'mail|gmail|email|e-mail|courriel'],
  ]),
  Q('Citez une tâche ménagère que personne n’aime faire.', 'Famille', 'facile', [
    ['La vaisselle', 34, 'vaisselle|faire la vaisselle'],
    ['Le repassage', 26, 'repasser|repassage'],
    ['Le ménage', 14, 'nettoyer|aspirateur|passer l’aspirateur'],
    ['Nettoyer les toilettes', 12, 'toilettes|wc'],
    ['Sortir les poubelles', 8, 'poubelles|poubelle'],
    ['Étendre le linge', 6, 'linge|lessive|machine'],
  ]),
  Q('Citez quelque chose que l’on fait lors d’un premier rendez-vous amoureux.', 'Relations', 'difficile', [
    ['Aller au restaurant', 32, 'restaurant|resto|dîner|diner'],
    ['Boire un verre', 22, 'verre|bar|apéro|café'],
    ['Aller au cinéma', 16, 'cinéma|ciné|film'],
    ['Se promener', 12, 'promenade|balade|marcher'],
    ['S’embrasser', 8, 'bisou|baiser|embrasser'],
    ['Parler', 5, 'discuter|faire connaissance|discussion'],
    ['Offrir des fleurs', 3, 'fleurs|bouquet|rose'],
    ['Être en retard', 2, 'retard'],
  ]),
  Q('Citez une ville française célèbre.', 'France', 'difficile', [
    ['Paris', 40, ''],
    ['Marseille', 18, ''],
    ['Lyon', 14, ''],
    ['Bordeaux', 8, ''],
    ['Nice', 7, ''],
    ['Toulouse', 6, ''],
    ['Lille', 4, ''],
    ['Strasbourg', 3, ''],
  ]),
  Q('Citez quelque chose que l’on retrouve dans un anniversaire d’enfant.', 'Enfants', 'difficile', [
    ['Un gâteau', 35, 'gâteau d’anniversaire|gâteau|gateau'],
    ['Des bougies', 20, 'bougie'],
    ['Des ballons', 15, 'ballon|baudruches'],
    ['Des cadeaux', 12, 'cadeau|présents'],
    ['Des bonbons', 7, 'bonbon|friandises'],
    ['Des chapeaux pointus', 5, 'chapeaux|chapeau|cotillons'],
    ['Un clown', 4, 'magicien|animateur'],
    ['Des jeux', 2, 'jeu|chasse au trésor'],
  ]),
];
